ADF7030-1 Device Drivers API Reference Manual: Patch Interface
Patch Interface
ADF7030-1 Driver
Data Structures
union crc_config_type
struct PATCH_CHECKSUM_DESCRIPTOR_Type
struct PATCH_DESCRIPTOR_Type
struct PATCH_INFO_Type
struct PATCH_SECTION_Type
Macros
#define adf7030_1__ReadPatchCheckumInfo(pSPIDevInfo, pPATCH, pPATCH_CHECKSUM)
#define adf7030_1__VerifyPatchCheckumInfo(pSPIDevInfo, pPATCH, pPATCH_CHECKSUM)
#define adf7030_1__WritePatchCheckumInfo(pSPIDevInfo, pPATCH, pPATCH_CHECKSUM)
Typedefs
typedef union crc_config_type CRC_CONFIG_Type
typedef struct PATCH_CHECKSUM_DESCRIPTOR_Type PATCH_CHECKSUM_DESCRIPTOR_Type
typedef struct PATCH_SECTION_Type PATCH_SECTION_Type
typedef PATCH_INFO_Type version_info_t
Functions
ADI_ADF7030_1_RESULT adf7030_1__ReadPatch (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, PATCH_DESCRIPTOR_Type *pPATCH)
Function call to readback the patch from Radio PHY.
ADI_ADF7030_1_RESULT adf7030_1__ReadPatchBlock (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type *pBlock)
Function to read a single Patch block to the PHY Radio.
ADI_ADF7030_1_RESULT adf7030_1__SelfCheckPatch (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, PATCH_DESCRIPTOR_Type *pPATCH, bool bCHECK, ADI_ADF7030_1_INTPIN eIntPin, ADI_ADF7030_1_RADIO_STATE eCmd, PATCH_CHECKSUM_DESCRIPTOR_Type *pCHECKSUM_CFG)
Function call to perform PHY Radio patch self-checking.
ADI_ADF7030_1_RESULT adf7030_1__SetupPatch (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint16_t SetupSeq, bool bCHECK)
Function call to setup the patch.
ADI_ADF7030_1_RESULT adf7030_1__VerifyPatch (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, PATCH_DESCRIPTOR_Type *pPATCH)
Function call to verify the integrity of the patch.
ADI_ADF7030_1_RESULT adf7030_1__VerifyPatchBlock (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type *pBlock)
Function to verify content of a single Patch block in the PHY.
ADI_ADF7030_1_RESULT adf7030_1__WritePatch (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, PATCH_DESCRIPTOR_Type *pPATCH)
Function call to write patch to Radio PHY.
ADI_ADF7030_1_RESULT adf7030_1__WritePatchBlock (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type *pBlock)
Function to write a single Patch block to the PHY Radio.
ADI_ADF7030_1_RESULT adf7030_1__XferChecksum (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, PATCH_DESCRIPTOR_Type *pPATCH, PATCH_CHECKSUM_DESCRIPTOR_Type *pPATCH_CHECKSUM, bool bREAD_nWRITE, bool bCHECK_ONLY)
Generic Patch checksum configuration transfers function between Host and the Radio PHY.
ADI_ADF7030_1_RESULT adf7030_1__XferPatch (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, PATCH_DESCRIPTOR_Type *pPATCH, bool bREAD_nWRITE, bool bCHECK_ONLY)
Generic Patch transfers function between Host and the Radio PHY.
ADI_ADF7030_1_RESULT adf7030_1__XferPatchBlock (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type *pBLOCK, bool bREAD_nWRITE, bool bCHECK_ONLY)
Generic Patch Section transfer function between Host and the Radio PHY.
Detailed Description
Macro Definition Documentation
adf7030_1__ReadPatchCheckumInfo
#define adf7030_1__ReadPatchCheckumInfo (pSPIDevInfo, pPATCH, pPATCH_CHECKSUM)
Value:
adf7030_1__XferChecksum(pSPIDevInfo, \
                                                                                                         (PATCH_DESCRIPTOR_Type *)pPATCH, \
                                                                                                         (PATCH_CHECKSUM_DESCRIPTOR_Type *)pPATCH_CHECKSUM, \
                                                                                                         (bool)PHY_MEM_READ, \
                                                                                                         false )
Definition at line 196 of file adf7030-1__patch.h.
adf7030_1__VerifyPatchCheckumInfo
#define adf7030_1__VerifyPatchCheckumInfo (pSPIDevInfo, pPATCH, pPATCH_CHECKSUM)
Value:
adf7030_1__XferChecksum(pSPIDevInfo,  \
                                                                                                         (PATCH_DESCRIPTOR_Type *)pPATCH, \
                                                                                                         (PATCH_CHECKSUM_DESCRIPTOR_Type *)pPATCH_CHECKSUM, \
                                                                                                         (bool)PHY_MEM_READ, \
                                                                                                         true )
Definition at line 201 of file adf7030-1__patch.h.
adf7030_1__WritePatchCheckumInfo
#define adf7030_1__WritePatchCheckumInfo (pSPIDevInfo, pPATCH, pPATCH_CHECKSUM)
Value:
adf7030_1__XferChecksum(pSPIDevInfo, \
                                                                                                         (PATCH_DESCRIPTOR_Type *)pPATCH, \
                                                                                                         (PATCH_CHECKSUM_DESCRIPTOR_Type *)pPATCH_CHECKSUM, \
                                                                                                         (bool)PHY_MEM_WRITE, \
                                                                                                         false )
Definition at line 191 of file adf7030-1__patch.h.
Function Documentation
adf7030_1__ReadPatch()
ADI_ADF7030_1_RESULT adf7030_1__ReadPatch (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, PATCH_DESCRIPTOR_Type * pPATCH)
Function call to readback the patch from Radio PHY.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in|out] pPatch Pointer to Host "patch" descriptor.
Note
This function only readback patch data from the PHY. pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR] could be modified.
Returns
Status
ADI_ADF7030_1_SUCCESS If the patch was readback successfully in the Host.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the patch transfert failed.
Definition at line 149 of file adf7030-1__patch.c.
References adf7030_1__XferPatch().
adf7030_1__ReadPatchBlock()
ADI_ADF7030_1_RESULT adf7030_1__ReadPatchBlock (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type * pBlock)
Function to read a single Patch block to the PHY Radio.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in|out] pBlock Pointer to single Host patch memory block.
Note
This function modifies pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the Patch block has been read back into pBlock->pdata.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the Patch block could not be read.
Definition at line 500 of file adf7030-1__patch.c.
References adf7030_1__XferPatchBlock().
adf7030_1__SelfCheckPatch()
ADI_ADF7030_1_RESULT adf7030_1__SelfCheckPatch (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, PATCH_DESCRIPTOR_Type * pPATCH, bool bCHECK, ADI_ADF7030_1_INTPIN eIntPin, ADI_ADF7030_1_RADIO_STATE eCmd, PATCH_CHECKSUM_DESCRIPTOR_Type * pCHECKSUM_CFG)
Function call to perform PHY Radio patch self-checking.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pPatch Pointer to Host "patch" descriptor.
[in] bCHECK Boolean -TRUE to verify the Inject sequence in the PHY -FALSE to discard any verifications
[in] eIntPin Interrupt id (ADI_ADF7030_1_INTPIN) to be used.
[in] eCmd PHY Radio Command to execute to trigger the start of the PHY Radio selftest internal routine. See ADI_ADF7030_1_RADIO_STATE enum for available commands.
[in] pCHECKSUM_CFG Pointer to Host "patch" checksum configuration descriptor. If NULL, the adf7030_1__SelfCheckPatch() will use the default provided with the "patch" header file.
Returns
Status
ADI_ADF7030_1_SUCCESS If the patch intergrity is correct.
ADI_ADF7030_1_FAILURE If the patch intergrity is incorrect.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the patch is different.
Definition at line 217 of file adf7030-1__patch.c.
References adf7030_1__VerifyPatchBlock(), adf7030_1__WritePatchBlock(), ADI_ADF7030_1_SUCCESS, PATCH_DESCRIPTOR_Type::BLOCKS, PATCH_DESCRIPTOR_Type::CheckBlockId, and PATCH_DESCRIPTOR_Type::pChecksum.
adf7030_1__SetupPatch()
ADI_ADF7030_1_RESULT adf7030_1__SetupPatch (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint16_t SetupSeq, bool bCHECK)
Function call to setup the patch.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] SetupSeq Setup patch sequence desired:
InjectSeq to enable the patch
EjectSeq to disable the patch
CheckSeq to enable patch selfcheck and auto inject
[in] bCHECK Boolean -TRUE to verify the Inject sequence in the PHY -FALSE to discard any verifications
Note
This function assume the following the patch has already been transfered and that its integrity is valid. User can check the Ram for the patch presence by calling the function adf7030_1__VerifyPatch().
Returns
Status
ADI_ADF7030_1_SUCCESS If the Inject sequence was succesfull.
ADI_ADF7030_1_FAILURE If the Inject sequence was not correct.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the Inject failed.
Definition at line 408 of file adf7030-1__patch.c.
References adf7030_1__SPI_wr_word_b_a(), ADI_ADF7030_1_FAILURE, and ADI_ADF7030_1_SUCCESS.
adf7030_1__VerifyPatch()
ADI_ADF7030_1_RESULT adf7030_1__VerifyPatch (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, PATCH_DESCRIPTOR_Type * pPATCH)
Function call to verify the integrity of the patch.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pPatch Pointer to Host "patch" descriptor.
Note
This function only disable the patch, it can be re-enable at a later stage by calling the adf7030_1__InjectPatch() function. This function modifies pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the patch in the PHY matches the reference in the Host.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the patch is different.
Definition at line 179 of file adf7030-1__patch.c.
References adf7030_1__XferPatch().
adf7030_1__VerifyPatchBlock()
ADI_ADF7030_1_RESULT adf7030_1__VerifyPatchBlock (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type * pBlock)
Function to verify content of a single Patch block in the PHY.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pBlock Pointer to single Host patch memory block.
Note
This function modifies pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the Patch block in the PHY matches the reference in the Host.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the Patch block of the PHY is different than the reference in the Host.
Definition at line 527 of file adf7030-1__patch.c.
References adf7030_1__XferPatchBlock().
Referenced by adf7030_1__SelfCheckPatch().
adf7030_1__WritePatch()
ADI_ADF7030_1_RESULT adf7030_1__WritePatch (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, PATCH_DESCRIPTOR_Type * pPATCH)
Function call to write patch to Radio PHY.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pPatch Pointer to Host "patch" descriptor.
Note
This function only transfert patch data to the PHY. Patch must be enabled at a later stage by calling the adf7030_1__InjectPatch() function. This function modifies pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the patch was written successfully in the Host.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the patch transfert failed.
Definition at line 121 of file adf7030-1__patch.c.
References adf7030_1__XferPatch().
adf7030_1__WritePatchBlock()
ADI_ADF7030_1_RESULT adf7030_1__WritePatchBlock (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type * pBlock)
Function to write a single Patch block to the PHY Radio.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pBlock Pointer to single Host patch memory block.
Note
This function modifies pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the Patch block has been written to the PHY.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the Patch block could not be written.
Definition at line 473 of file adf7030-1__patch.c.
References adf7030_1__XferPatchBlock().
Referenced by adf7030_1__SelfCheckPatch().
adf7030_1__XferChecksum()
ADI_ADF7030_1_RESULT adf7030_1__XferChecksum (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, PATCH_DESCRIPTOR_Type * pPATCH, PATCH_CHECKSUM_DESCRIPTOR_Type * pPATCH_CHECKSUM, bool bREAD_nWRITE, bool bCHECK_ONLY)
Generic Patch checksum configuration transfers function between Host and the Radio PHY.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pPatch Pointer to Host "patch" descriptor.
[in|out] pPATCH_CHECKSUM Pointer to Host "patch" checksum configuration descriptor.
[in] bREAD_nWRITE Boolean -TRUE to write Patch from Host to the Radio PHY -FALSE to read Patch from Radio PHY back to Host
[in] bCHECK_ONLY Boolean -TRUE to check PHY patch versus Host Reference -FALSE [D] to perform READ_nWRITE operation
Note
This function modifies pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
Definition at line 728 of file adf7030-1__patch.c.
References DATA_BLOCK_DESCRIPTOR_Type::Addr, adf7030_1__XferPatchBlock(), PATCH_DESCRIPTOR_Type::BLOCKS, PATCH_DESCRIPTOR_Type::InfoBlockId, and DATA_BLOCK_DESCRIPTOR_Type::pData.
adf7030_1__XferPatch()
ADI_ADF7030_1_RESULT adf7030_1__XferPatch (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, PATCH_DESCRIPTOR_Type * pPATCH, bool bREAD_nWRITE, bool bCHECK_ONLY)
Generic Patch transfers function between Host and the Radio PHY.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in|out] pPatch Pointer to Host "patch" descriptor.
[in] bREAD_nWRITE Boolean -TRUE to write Patch from Host to the Radio PHY -FALSE to read Patch from Radio PHY back to Host
[in] bCHECK_ONLY Boolean -TRUE to check PHY patch versus Host Reference -FALSE [D] to perform READ_nWRITE operation
Note
This function modifies pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
Definition at line 560 of file adf7030-1__patch.c.
References adf7030_1__XferPatchBlock(), ADI_ADF7030_1_SPI_COMM_FAILED, ADI_ADF7030_1_SUCCESS, PATCH_DESCRIPTOR_Type::BLOCKS, PATCH_DESCRIPTOR_Type::CheckBlockId, PATCH_DESCRIPTOR_Type::InfoBlockId, and PATCH_DESCRIPTOR_Type::nbBlock.
Referenced by adf7030_1__ReadPatch(), adf7030_1__VerifyPatch(), and adf7030_1__WritePatch().
adf7030_1__XferPatchBlock()
ADI_ADF7030_1_RESULT adf7030_1__XferPatchBlock (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type * pBLOCK, bool bREAD_nWRITE, bool bCHECK_ONLY)
Generic Patch Section transfer function between Host and the Radio PHY.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in|out] pBLOCK Pointer to Host "patch" sub-block descriptor.
[in] bREAD_nWRITE Boolean -TRUE to write Patch from Host to the Radio PHY -FALSE to read Patch from Radio PHY back to Host
[in] bCHECK_ONLY Boolean -TRUE to check PHY patch versus Host Reference -FALSE [D] to perform READ_nWRITE operation
Note
This function modifies pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
Definition at line 607 of file adf7030-1__patch.c.
References DATA_BLOCK_DESCRIPTOR_Type::Addr, adf7030_1__SPI_FindMMapPointer(), adf7030_1__SPI_rd_cmp_byte_p_a(), adf7030_1__SPI_SetMMapCustomPntr0(), ADI_ADF7030_1_SPI_COMM_FAILED, ADI_ADF7030_1_SUCCESS, and DATA_BLOCK_DESCRIPTOR_Type::pData.
Referenced by adf7030_1__ReadPatchBlock(), adf7030_1__VerifyPatchBlock(), adf7030_1__WritePatchBlock(), adf7030_1__XferChecksum(), and adf7030_1__XferPatch().