ADF7030-1 Device Drivers API Reference Manual: SPI Communication Interface
SPI Communication Interface
ADF7030-1 Driver
Macros
#define adf7030_1__SPI_rd_byte_b_a(pSPIDevInfo, pntrID, AddrIn, num_xfrs, pDataOut) adf7030_1__SPI_rd_cmp_byte_b_a(pSPIDevInfo, pntrID, AddrIn, num_xfrs, pDataOut, NULL)
#define adf7030_1__SPI_rd_byte_p_a(pSPIDevInfo, pntrID, num_xfrs, pDataOut) adf7030_1__SPI_rd_cmp_byte_p_a(pSPIDevInfo, pntrID, num_xfrs, pDataOut, NULL)
#define adf7030_1__SPI_rd_word_b_a(pSPIDevInfo, AddrIn, num_xfrs, pDataOut) adf7030_1__SPI_rd_cmp_word_b_a(pSPIDevInfo, AddrIn, num_xfrs, pDataOut, NULL)
#define adf7030_1__SPI_rd_word_b_p(pSPIDevInfo, pntrID, num_xfrs, pDataOut) adf7030_1__SPI_rd_cmp_word_b_p(pSPIDevInfo, pntrID, num_xfrs, pDataOut, NULL)
Typedefs
typedef ADI_ADF7030_1_RESULT(* ADI_ADF7030_1_SPI_Xfer) (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t cmdOffset, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE PNTR_ID, uint32_t Addr, uint32_t nbBytes, void *pDataIO, void *pDataRef)
Enumerations
enum ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE {
PNTR_SETUP_ADDR = 0,
PNTR_SRAM_ADDR = 1,
PNTR_MCR_LOW = 2,
PNTR_MCR_HIGH = 3,
PNTR_IRQ_CTRL_ADDR = 4,
PNTR_CUSTOM0_ADDR = 5,
PNTR_CUSTOM1_ADDR = 6,
PNTR_CUSTOM2_ADDR = 7
}
enum ADI_ADF7030_1_RADIO_SPI_RATE_TYPE {
DEFAULT_SPI_RATE = 0,
FAST_SPI_RATE = 1
}
enum ADI_ADF7030_1_RADIO_SPI_TRX_TYPE {
SPI_WRITE = 0,
SPI_READ = 1
}
Functions
ADI_ADF7030_1_RESULT adf7030_1__SPI_block_transaction (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t cmdOffset, uint32_t nbBytes, void *pDataIO, void *pDataRef)
Generic SPI Block Read/Write a number of words(s) to the adf7030-1.
ADI_ADF7030_1_RESULT adf7030_1__SPI_Block_Xfer (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t cmdOffset, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE PNTR_ID, uint32_t Addr, uint32_t nbBytes, void *pDataIO, void *pDataRef)
Generic function to read or write a number of bytes between the Host and the PHY adf703x.
ADI_ADF7030_1_RESULT adf7030_1__SPI_Block_Xfer__fast (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t cmdOffset, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE PNTR_ID, uint32_t Addr, uint32_t nbBytes, void *pDataIO, void *pDataRef)
Generic function to read or write a number of bytes between the Host and the PHY adf703x.
void adf7030_1__SPI_FindMMapPointer (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t Addr, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE *pPNTR_ID, int32_t *pByteOffset)
This function return the best Pointer id + offset for subsequent SPI transfert to the PHY "Addr" provided.
ADI_ADF7030_1_RESULT adf7030_1__SPI_GetMMapPointers (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo)
Get SPI Radio mmap pointers access.
ADI_ADF7030_1_RESULT adf7030_1__SPI_Init (ADI_ADF7030_1_HANDLE const hDevice)
Initializes SPI device for communication with the adf7030-1 PHY.
ADI_ADF7030_1_RESULT adf7030_1__SPI_rd_cmp_byte_b_a (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE pntrID, uint32_t AddrIn, uint32_t num_xfrs, uint8_t *pDataOut, uint8_t *pDataRef)
Read & Compare a number of bytes(s) from memory of the adf7030-1 to Host starting at location pointed by "pntr" + AddrIn offset Generic 8bits bloc address read from memory (HRM 1.4.4.2.4)
ADI_ADF7030_1_RESULT adf7030_1__SPI_rd_cmp_byte_p_a (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE pntrID, uint32_t num_xfrs, uint8_t *pDataOut, uint8_t *pDataRef)
Read & Compare a number of bytes(s) from memory of the adf7030-1 to Host starting at location pointed by "pntr" Generic 8bits bloc pointer read from memory (HRM 1.4.4.2.6/10) This Function should be used when writing a large block of unaligned data to the radio (above ADI_SPI_MEMORY_SIZE).
ADI_ADF7030_1_RESULT adf7030_1__SPI_rd_cmp_word_b_a (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t AddrIn, uint32_t num_xfrs, uint32_t *pDataOut, uint32_t *pDataRef)
Read & Compare a number of word(s) from the adf7030-1 to memory of Host Generic 32bits bloc address read from memory (HRM 1.4.4.2.3). This Function should be used when reading a large block of 32bits word from the radio (above ADI_SPI_MEMORY_SIZE).
ADI_ADF7030_1_RESULT adf7030_1__SPI_rd_cmp_word_b_p (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE pntrID, uint32_t num_xfrs, uint32_t *pDataOut, uint32_t *pDataRef)
Read & Compare a number of word(s) from memory of the adf7030-1 to Host starting at location pointed by "pntr" Generic 32bits bloc pointer read from memory (HRM 1.4.4.2.5/9)
void adf7030_1__SPI_ReadWrite_Fast (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint8_t *pTX_DATA, uint8_t *pRX_DATA, uint32_t nSize)
Custom FAST API for Read/Write a number of byte(s) to the adf7030-1.
ADI_ADF7030_1_RESULT adf7030_1__SPI_SetMMapCustomPntr0 (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t Addr)
Change the SPI Radio mmap custom pointers 0 location.
ADI_ADF7030_1_RESULT adf7030_1__SPI_SetMMapPointers (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo)
Set SPI Radio mmap pointers access.
ADI_ADF7030_1_RESULT adf7030_1__SPI_SetSpeed (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_RADIO_SPI_RATE_TYPE eSPIRate)
Change SPI Host to PHY Communication bitrate.
ADI_ADF7030_1_RESULT adf7030_1__SPI_UnInit (ADI_ADF7030_1_HANDLE const hDevice)
Uninitializes SPI device used to communication with the adf7030-1 PHY.
ADI_ADF7030_1_RESULT adf7030_1__SPI_wr_byte_b_a (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE pntrID, uint32_t AddrIn, uint32_t num_xfrs, uint8_t *pDataIn)
Write a number of byte(s) from Host to memory of the adf7030-1 starting at location pointed by "pntr" + AddrIn Generic 8bits bloc address write to memory (HRM 1.4.4.2.4)
ADI_ADF7030_1_RESULT adf7030_1__SPI_wr_byte_p_a (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE pntrID, uint32_t num_xfrs, uint8_t *pDataIn)
Write a number of byte(s) from Host to memory of the adf7030-1 starting at location pointed by "pntr". Generic 8bits bloc pointer write to memory (HRM 1.4.4.2.6/10) This Function should be used when writing a large block of 8bits word to the radio (above ADI_SPI_MEMORY_SIZE).
ADI_ADF7030_1_RESULT adf7030_1__SPI_wr_word_b_a (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t AddrIn, uint32_t num_xfrs, uint32_t *pDataIn)
Write a number of word(s) from Host to memory of the adf7030-1 Generic 32bits bloc address write to memory (HRM 1.4.4.2.3). This Function should be used when writing a large block of 32bits word to the radio (above ADI_SPI_MEMORY_SIZE).
ADI_ADF7030_1_RESULT adf7030_1__SPI_wr_word_b_p (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE pntrID, uint32_t num_xfrs, uint32_t *pDataIn)
Write a number of word(s) from Host to memory of the adf7030-1 starting at location pointed by "pntr" Generic 32bits bloc pointer write to memory (HRM 1.4.4.2.5/9) This Function should be used when writing a large block of 32bits word to the radio (above ADI_SPI_MEMORY_SIZE).
ADI_ADF7030_1_RESULT adf7030_1__SPI_Xfer_ReadBuff (void *pDest, void *pSrc, void *pRef, uint32_t nBytes, uint32_t mode)
Copy number of byte(s) from SPI RX buffer into Host memory space.
void adf7030_1__SPI_Xfer_WriteBuff (void *pDest, void *pSrc, uint32_t nBytes, uint32_t mode, uint32_t op)
Copy number of byte(s) from Host memory space into SPI TX buffer.
Detailed Description
Enumeration Type Documentation
ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE
enum ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE
Enumeration of different SPI pointer type
Definition at line 51 of file adf7030-1__spi.h.
ADI_ADF7030_1_RADIO_SPI_RATE_TYPE
enum ADI_ADF7030_1_RADIO_SPI_RATE_TYPE
Enumeration of Host SPI Rate
Definition at line 69 of file adf7030-1__spi.h.
ADI_ADF7030_1_RADIO_SPI_TRX_TYPE
enum ADI_ADF7030_1_RADIO_SPI_TRX_TYPE
Enumeration of Host SPI transaction type
Definition at line 63 of file adf7030-1__spi.h.
Function Documentation
adf7030_1__SPI_block_transaction()
ADI_ADF7030_1_RESULT adf7030_1__SPI_block_transaction (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t cmdOffset, uint32_t nbBytes, void * pDataIO, void * pDataRef)
Generic SPI Block Read/Write a number of words(s) to the adf7030-1.
Note
Blocking SPI transfert without DMA.
Parameters
[in] hSPIDevice Handle to Glue SPI peripheral device used to communicate with the adf7030-1.
[in] cmdOffset Byte location from where the spi frame starts in the spi_txbuf.
[in] nbBytes Number of Bytes transfert.
[in,out] pDataIO In TX, data is read from address pointed by pDataIO. In RX, data is written back at address pointed by pDataIO.
[in] pDataRef Pointer to the start of the Ref Host data block. If set, the SPI readback data will be compared with the data pointed by pDataRef. This can be used to compare data between Host and PHY directly within the readback.
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
Definition at line 1433 of file adf7030-1__spi.c.
References adf7030_1__SPI_SetSpeed().
adf7030_1__SPI_Block_Xfer()
ADI_ADF7030_1_RESULT adf7030_1__SPI_Block_Xfer (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t cmdOffset, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE PNTR_ID, uint32_t Addr, uint32_t nbBytes, void * pDataIO, void * pDataRef)
Generic function to read or write a number of bytes between the Host and the PHY adf703x.
Note
If the number of bytes to be transfered exceeds the maximum SPI buffer size allocated, the spi transfert is automatically cut down into smaller sub spi transaction until the transfer operation is completed. No buffer owerflow or boundary check is done.
Parameters
[in] hSPIDevice Handle to Glue SPI peripheral device used to communicate with the adf7030-1.
[in] cmdOffset Location within the spitx_buff where the spi command byte is located.
[in] PNTR_ID SPI pointer ID to use as base address for writing the block of data.
[in] AddrIn Address location at which the SPI write should start transfert in the PHY.
[in] nbBytes Number of bytes to read or write to be performed. If nbBytes is bigger than ADI_SPI_MEMORY_SIZE, the custom spi pntr0 will be used to transfert the data. The shadow pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR] and the PHY value (in the radio) will be restored to there original value.
[in|out] pDataIO Pointer to the start of the Host data block. On exit, pDataIO is pointing nbBytes away from its original value.
[in] pDataRef Pointer to the start of the Ref Host data block. If set, the SPI readback data will be compared with the data pointed by pDataRef. This can be used to compare data between Host and PHY directly within the readback.
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_SPI_DEV_FAILED If SPI interface configuration failed.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
Definition at line 1249 of file adf7030-1__spi.c.
References adi_adf7030_1_SPI_Info::PHY_PNTR, and adi_adf7030_1_SPI_Info::pSPI_TX_BUFF.
adf7030_1__SPI_Block_Xfer__fast()
ADI_ADF7030_1_RESULT adf7030_1__SPI_Block_Xfer__fast (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t cmdOffset, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE PNTR_ID, uint32_t Addr, uint32_t nbBytes, void * pDataIO, void * pDataRef)
Generic function to read or write a number of bytes between the Host and the PHY adf703x.
Note
This function is a faster implementation of adf7030_1__SPI_Block_Xfer() automatically call if "nbBytes" is less than the defined threshold ADF7030_1_SPI_FAST_SIZE_THRESHOLD. This function bypass the default API to initiate transfert via the SPI from the BSP and instead takes direct control of the SPI hardware.
Parameters
[in] hSPIDevice Handle to Glue SPI peripheral device used to communicate with the adf7030-1.
[in] cmdOffset Location within the spitx_buff where the spi command byte is located.
[in] PNTR_ID SPI ID pointer to use as base address for writing the block of data.
[in] AddrIn Address location at which the SPI write should start transfert in the PHY.
[in] nbBytes Number of bytes to read or write to be performed.
[in|out] pDataIO Pointer to the start of the Host data block. On exit, pDataIO is pointing nbBytes away from its original value.
[in] pDataRef Pointer to the start of the Ref Host data block. If set, the SPI readback data will be compared with the data pointed by pDataRef. This can be used to compare data between Host and PHY directly within the readback.
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_SPI_DEV_FAILED If SPI interface configuration failed.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
Definition at line 1119 of file adf7030-1__spi.c.
References adf7030_1__SPI_SetSpeed().
adf7030_1__SPI_FindMMapPointer()
void adf7030_1__SPI_FindMMapPointer (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t Addr, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE * pPNTR_ID, int32_t * pByteOffset)
This function return the best Pointer id + offset for subsequent SPI transfert to the PHY "Addr" provided.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] Addr Desired Radio PHY address.
[out] pPNTR_ID Pointer to PNTR_ID variable to access "Addr" location of mmap eg. pSPIDevInfo->PHY_PNTR[pPNTR_ID].
[out] ByteOffset Pointer to the positive byte offset variable between "Addr" and pSPIDevInfo->PHY_PNTR[pPNTR_ID].
Returns
None
Definition at line 375 of file adf7030-1__spi.c.
Referenced by adf7030_1__SPI_Xfer_Mem(), adf7030_1__XferDataBlock(), and adf7030_1__XferPatchBlock().
adf7030_1__SPI_GetMMapPointers()
ADI_ADF7030_1_RESULT adf7030_1__SPI_GetMMapPointers (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo)
Get SPI Radio mmap pointers access.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
Note
This function recall the content of PHY radio mmap pointers back into the pSPIDevInfo->PHY_PNTR[].
Returns
Status
ADI_ADF7030_1_SUCCESS If the readback of mmap pointers was succesfull.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the readback failed.
Definition at line 343 of file adf7030-1__spi.c.
References adi_adf7030_1_SPI_Info::PHY_PNTR.
adf7030_1__SPI_Init()
ADI_ADF7030_1_RESULT adf7030_1__SPI_Init (ADI_ADF7030_1_HANDLE const hDevice)
Initializes SPI device for communication with the adf7030-1 PHY.
Note
This function open the SPI peripheral in "blocking mode" without DMA transfert assistance. blablabla...
Parameters
[in] hDevice Handle to ADF3030-1 device instance.
Returns
Status
ADI_ADF7030_1_SUCCESS If SPI peripheral was succesfully initialise
ADI_ADF7030_1_SPI_DEV_FAILED [D] SPI peripheral failed to initialise
See also
adf7030_1__SPI_UnInit().
Definition at line 119 of file adf7030-1__spi.c.
References adf7030_1__SPI_SetSpeed(), ADI_ADF7030_1_SPI_DEV_FAILED, ADI_ADF7030_1_SUCCESS, adi_adf7030_1_SPI_Info::eChipSelect, adi_adf7030_1_SPI_Info::hDevInfo, adi_adf7030_1_SPI_Info::hSPIDevice, adi_adf7030_1_SPI_Info::nDeviceNum, adi_adf7030_1_SPI_Info::nMemorySize, adi_adf7030_1_device::pDevInfo, adi_adf7030_1_SPI_Info::pDevMemory, and adi_adf7030_1_info::SPIInfo.
Referenced by adf7030_1__Setup().
adf7030_1__SPI_rd_cmp_byte_b_a()
ADI_ADF7030_1_RESULT adf7030_1__SPI_rd_cmp_byte_b_a (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE pntrID, uint32_t AddrIn, uint32_t num_xfrs, uint8_t * pDataOut, uint8_t * pDataRef)
Read & Compare a number of bytes(s) from memory of the adf7030-1 to Host starting at location pointed by "pntr" + AddrIn offset Generic 8bits bloc address read from memory (HRM 1.4.4.2.4)
Note
If the number of bytes to be received exceeds the maximum SPI buffer size allocated, the spi transfert is automatically cut into smaller sub spi transaction until the writting operation is completed. No buffer owerflow or boundary check is done.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pntrID SPI pointer ID to use as base address for reading the block of data.
[in] AddrIn Address location at which the SPI read should start.
[in] num_xfrs Number of bytes read to be performed.
[out] pDataOut Pointer to the data block to be transmitted.
[in] pDataRef Pointer to the start of the Ref Host data block. If set, the SPI readback data will be compared with the data pointed by pDataRef. This can be used to compare data between Host and PHY directly within the readback.
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
Definition at line 873 of file adf7030-1__spi.c.
References adi_adf7030_1_SPI_Info::pSPI_TX_BUFF.
adf7030_1__SPI_rd_cmp_byte_p_a()
ADI_ADF7030_1_RESULT adf7030_1__SPI_rd_cmp_byte_p_a (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE pntrID, uint32_t num_xfrs, uint8_t * pDataOut, uint8_t * pDataRef)
Read & Compare a number of bytes(s) from memory of the adf7030-1 to Host starting at location pointed by "pntr" Generic 8bits bloc pointer read from memory (HRM 1.4.4.2.6/10) This Function should be used when writing a large block of unaligned data to the radio (above ADI_SPI_MEMORY_SIZE).
Note
If the number of bytes to be received exceeds the maximum SPI buffer size allocated, the spi transfert is automatically cut into smaller sub spi transaction until the writting operation is completed. No buffer owerflow or boundary check is done.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pntrID SPI pointer ID to use as base address for reading the block of data.
[in] num_xfrs Number of byte write to be performed.
[out] pDataOut Pointer to the data block to be transmitted.
[in] pDataRef Pointer to the start of the Ref Host data block. If set, the SPI readback data will be compared with the data pointed by pDataRef. This can be used to compare data between Host and PHY directly within the readback.
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
Definition at line 1027 of file adf7030-1__spi.c.
References adi_adf7030_1_SPI_Info::pSPI_TX_BUFF.
Referenced by adf7030_1__XferDataBlock(), and adf7030_1__XferPatchBlock().
adf7030_1__SPI_rd_cmp_word_b_a()
ADI_ADF7030_1_RESULT adf7030_1__SPI_rd_cmp_word_b_a (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t AddrIn, uint32_t num_xfrs, uint32_t * pDataOut, uint32_t * pDataRef)
Read & Compare a number of word(s) from the adf7030-1 to memory of Host Generic 32bits bloc address read from memory (HRM 1.4.4.2.3). This Function should be used when reading a large block of 32bits word from the radio (above ADI_SPI_MEMORY_SIZE).
Note
If the number of words to read exceeds the maximum SPI buffer size allocated, the spi transfert is automatically cut into smaller sub spi transaction until the reading operation is completed. No buffer owerflow or boundary check is done.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] AddrIn Address location at which the SPI write should start.
[in] num_xfrs Number of 32bits word write to be performed.
[out] pDataOut Pointer to the write back location in the host. On exit, pDataOut is pointing at the location of the AddrIn + num_xfrs of the host memory.
[in] pDataRef Pointer to the start of the Ref Host data block. If set, the SPI readback data will be compared with the data pointed by pDataRef. This can be used to compare data between Host and PHY directly within the readback.
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
See also
blabla()
Definition at line 563 of file adf7030-1__spi.c.
References adi_adf7030_1_SPI_Info::pSPI_TX_BUFF.
adf7030_1__SPI_rd_cmp_word_b_p()
ADI_ADF7030_1_RESULT adf7030_1__SPI_rd_cmp_word_b_p (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE pntrID, uint32_t num_xfrs, uint32_t * pDataOut, uint32_t * pDataRef)
Read & Compare a number of word(s) from memory of the adf7030-1 to Host starting at location pointed by "pntr" Generic 32bits bloc pointer read from memory (HRM 1.4.4.2.5/9)
Note
If the number of words to be received exceeds the maximum SPI buffer size allocated, the spi transfert is automatically cut into smaller sub spi transaction until the writting operation is completed. No buffer owerflow or boundary check is done.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pntrID SPI pointer ID to use as base address for reading the block of data.
[in] num_xfrs Number of 32bits word read to be performed.
[out] pDataOut Pointer to the write back location in the host.
[in] pDataRef Pointer to the start of the Ref Host data block. If set, the SPI readback data will be compared with the data pointed by pDataRef. This can be used to compare data between Host and PHY directly within the readback.
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
See also
blabla()
Definition at line 716 of file adf7030-1__spi.c.
References adi_adf7030_1_SPI_Info::pSPI_TX_BUFF.
adf7030_1__SPI_ReadWrite_Fast()
void adf7030_1__SPI_ReadWrite_Fast (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint8_t * pTX_DATA, uint8_t * pRX_DATA, uint32_t nSize)
Custom FAST API for Read/Write a number of byte(s) to the adf7030-1.
Note
Blocking SPI transfert without DMA nor IRQ, just uses FIFO status polling.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pTX_DATA Pointer to data to be transmitted.
[out] pRX_DATA Pointer where readback data is to be received.
[in] nSize Number of bytes to be transfered.
Returns
None
Definition at line 1573 of file adf7030-1__spi.c.
References adi_adf7030_1_SPI_Info::eChipSelect, and adi_adf7030_1_SPI_Info::hSPIDevice.
Referenced by adf7030_1__XferCmdPoll().
adf7030_1__SPI_SetMMapCustomPntr0()
ADI_ADF7030_1_RESULT adf7030_1__SPI_SetMMapCustomPntr0 (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t Addr)
Change the SPI Radio mmap custom pointers 0 location.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] Addr Value of the pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the "Addr" is within range for the SPI transfer.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If no PointerID is available.
Definition at line 428 of file adf7030-1__spi.c.
References adf7030_1__SPI_wr_word_b_p().
Referenced by adf7030_1__XferDataBlock(), and adf7030_1__XferPatchBlock().
adf7030_1__SPI_SetMMapPointers()
ADI_ADF7030_1_RESULT adf7030_1__SPI_SetMMapPointers (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo)
Set SPI Radio mmap pointers access.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
Note
This function copy the content of pSPIDevInfo->PHY_PNTR[] into the PHY radio.
Returns
Status
ADI_ADF7030_1_SUCCESS If the configuration of mmap pointers was succesfull.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the configuration of mmap pointers failed.
Definition at line 315 of file adf7030-1__spi.c.
References adi_adf7030_1_SPI_Info::PHY_PNTR.
adf7030_1__SPI_SetSpeed()
ADI_ADF7030_1_RESULT adf7030_1__SPI_SetSpeed (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_RADIO_SPI_RATE_TYPE eSPIRate)
Change SPI Host to PHY Communication bitrate.
Note
Default speed is set to 3.5MBps, anything faster should really used DMA operation mode which is corrently not supported
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] RateHz Target bitrate (in Hz) for SPI communication.
Returns
Status
ADI_ADF7030_1_SUCCESS If SPI peripheral was succesfully released
ADI_ADF7030_1_SPI_DEV_FAILED [D] SPI peripheral failed to release
See also
adi_spi_SetBitrate().
Definition at line 272 of file adf7030-1__spi.c.
Referenced by adf7030_1__SPI_block_transaction(), adf7030_1__SPI_Block_Xfer__fast(), and adf7030_1__SPI_Init().
adf7030_1__SPI_UnInit()
ADI_ADF7030_1_RESULT adf7030_1__SPI_UnInit (ADI_ADF7030_1_HANDLE const hDevice)
Uninitializes SPI device used to communication with the adf7030-1 PHY.
Note
This function release and deallocate memory used by the SPI peripheral
Parameters
[in] hDevice Handle to ADF3030-1 device instance.
Returns
Status
ADI_ADF7030_1_SUCCESS If SPI peripheral was succesfully released
ADI_ADF7030_1_SPI_DEV_FAILED [D] SPI peripheral failed to release
See also
adf7030_1__SPI_Init().
Definition at line 217 of file adf7030-1__spi.c.
References ADI_ADF7030_1_SPI_DEV_FAILED, ADI_ADF7030_1_SUCCESS, adi_adf7030_1_SPI_Info::hDevInfo, adi_adf7030_1_SPI_Info::hSPIDevice, adi_adf7030_1_device::pDevInfo, and adi_adf7030_1_info::SPIInfo.
Referenced by adf7030_1__Close().
adf7030_1__SPI_wr_byte_b_a()
ADI_ADF7030_1_RESULT adf7030_1__SPI_wr_byte_b_a (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE pntrID, uint32_t AddrIn, uint32_t num_xfrs, uint8_t * pDataIn)
Write a number of byte(s) from Host to memory of the adf7030-1 starting at location pointed by "pntr" + AddrIn Generic 8bits bloc address write to memory (HRM 1.4.4.2.4)
Note
If the number of bytes to be transmitted exceeds the maximum SPI buffer size allocated, the spi transfert is automatically cut into smaller sub spi transaction until the writting operation is completed. No buffer owerflow or boundary check is done.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pntrID SPI pointer ID to use as base address for writing the block of data.
[in] AddrIn Address location at which the SPI write should start.
[in] num_xfrs Number of byte write to be performed.
[in] pDataIn Pointer to the data block to be transmitted.
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
Definition at line 792 of file adf7030-1__spi.c.
References adi_adf7030_1_SPI_Info::pSPI_TX_BUFF.
adf7030_1__SPI_wr_byte_p_a()
ADI_ADF7030_1_RESULT adf7030_1__SPI_wr_byte_p_a (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE pntrID, uint32_t num_xfrs, uint8_t * pDataIn)
Write a number of byte(s) from Host to memory of the adf7030-1 starting at location pointed by "pntr". Generic 8bits bloc pointer write to memory (HRM 1.4.4.2.6/10) This Function should be used when writing a large block of 8bits word to the radio (above ADI_SPI_MEMORY_SIZE).
Note
If the number of bytes to be transmitted exceeds the maximum SPI buffer size allocated, the spi transfert is automatically cut into smaller sub spi transaction until the writting operation is completed. No buffer owerflow or boundary check is done.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pntrID SPI pointer ID to use as base address for reading the block of data.
[in] num_xfrs Number of byte write to be performed.
[in] pDataIn Pointer to the data block to be transmitted.
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
Definition at line 951 of file adf7030-1__spi.c.
References adi_adf7030_1_SPI_Info::pSPI_TX_BUFF.
adf7030_1__SPI_wr_word_b_a()
ADI_ADF7030_1_RESULT adf7030_1__SPI_wr_word_b_a (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t AddrIn, uint32_t num_xfrs, uint32_t * pDataIn)
Write a number of word(s) from Host to memory of the adf7030-1 Generic 32bits bloc address write to memory (HRM 1.4.4.2.3). This Function should be used when writing a large block of 32bits word to the radio (above ADI_SPI_MEMORY_SIZE).
Note
If the number of words to be transfered exceeds the maximum SPI buffer size allocated, the spi transfert is automatically cut into smaller sub spi transaction until the writting operation is completed. No buffer owerflow or boundary check is done.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] AddrIn Address location at which the SPI write should start.
[in] num_xfrs Number of 32bits word write to be performed.
[in] pDataIn Pointer to the data block to be transmitted. On exit, pDataIn is pointing at the location of the AddrIn + num_xfrs of the host memory.
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
See also
blabla()
Definition at line 482 of file adf7030-1__spi.c.
References adi_adf7030_1_SPI_Info::pSPI_TX_BUFF.
Referenced by adf7030_1__IRQ_ClrStatus(), adf7030_1__IRQ_SetMap(), and adf7030_1__SetupPatch().
adf7030_1__SPI_wr_word_b_p()
ADI_ADF7030_1_RESULT adf7030_1__SPI_wr_word_b_p (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_RADIO_SPI_PNTR_TYPE pntrID, uint32_t num_xfrs, uint32_t * pDataIn)
Write a number of word(s) from Host to memory of the adf7030-1 starting at location pointed by "pntr" Generic 32bits bloc pointer write to memory (HRM 1.4.4.2.5/9) This Function should be used when writing a large block of 32bits word to the radio (above ADI_SPI_MEMORY_SIZE).
Note
If the number of words to be transfered exceeds the maximum SPI buffer size allocated, the spi transfert is automatically cut into smaller sub spi transaction until the writting operation is completed. No buffer owerflow or boundary check is done.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pntrID SPI pointer ID to use as base address for writing the block of data.
[in] num_xfrs Number of 32bits word write to be performed.
[in] pDataIn Pointer to the data block to be transmitted.
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
See also
blabla()
Definition at line 640 of file adf7030-1__spi.c.
References adi_adf7030_1_SPI_Info::pSPI_TX_BUFF.
Referenced by adf7030_1__SPI_SetMMapCustomPntr0().
adf7030_1__SPI_Xfer_ReadBuff()
ADI_ADF7030_1_RESULT adf7030_1__SPI_Xfer_ReadBuff (void * pDest, void * pSrc, void * pRef, uint32_t nBytes, uint32_t mode)
Copy number of byte(s) from SPI RX buffer into Host memory space.
Note
This function handles both words and bytes SPI transfers.
Parameters
[in] pDest Pointer to the Host memory location where data from pSrc (SPI API RX buffer) should be copied.
[in] pSrc Pointer to the SPI API RX buffer location where the data pointed by pDest will be copied.
[in] pRef Pointer to the start of the Ref Host data block. If set, the SPI readback pointed by pSrc is compared with the data pointed by pRef. This can be used to compare data between Host and PHY directly within the readback.
[in] nBytes Number of byte to copy
[in] mode -0 for SPI byte (8bits) operation. -1 for SPI word (32bits) operation.
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
Definition at line 1744 of file adf7030-1__spi.c.
References ADI_ADF7030_1_SPI_COMM_FAILED, and ADI_ADF7030_1_SUCCESS.
adf7030_1__SPI_Xfer_WriteBuff()
void adf7030_1__SPI_Xfer_WriteBuff (void * pDest, void * pSrc, uint32_t nBytes, uint32_t mode, uint32_t op)
Copy number of byte(s) from Host memory space into SPI TX buffer.
Note
This function handles both words and bytes transfers for Read and Write SPI transfers.
Parameters
[in] pDest Pointer to the SPI API TX buffer location where the data pointed by pSrc will be copied.
[in] pSrc Pointer to the data that should be copied.
[in] nBytes Number of byte to copy
[in] mode -0 for SPI byte (8bits) operation. -1 for SPI word (32bits) operation.
[in] op -0 for SPI Write operation. -Else SPI Read operation.
Returns
None
Definition at line 1665 of file adf7030-1__spi.c.