ADF7030-1 Device Drivers API Reference Manual: Memory Interface
Memory Interface
ADF7030-1 Driver
Data Structures
struct BLOCK_XFER_DESCRIPTOR_Type
struct config_info_t
struct DATA_BLOCK_DESCRIPTOR_Type
struct MEM_CFG_DESCRIPTOR_Type
struct MEM_DESCRIPTOR_Type
struct RANDOM_XFER_DESCRIPTOR_Type
Macros
#define adf7030_1__READ_FIELD(fName)
#define adf7030_1__READ_REG(rName)
#define adf7030_1__WRITE_FIELD(fName, fValue)
#define adf7030_1__WRITE_REG(rName, rValue)
#define PHY_MEM_READ true
#define PHY_MEM_WRITE false
Functions
bool adf7030_1__MEM_CheckByteAccess (uint32_t nAddr)
Generic Function to check if byte rw operation is permitted.
ADI_ADF7030_1_RESULT adf7030_1__ReadConfig (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, MEM_CFG_DESCRIPTOR_Type *pCONFIG)
Function call to read Configuration from Radio PHY.
ADI_ADF7030_1_RESULT adf7030_1__ReadDataBlock (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type *pBLOCK)
Function call to read the Data block.
ADI_ADF7030_1_RESULT adf7030_1__ReadPartiaDataBlock (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type *pBLOCK, uint16_t Offset, uint16_t Size)
Function call to partially read a section of the Host Data block.
uint32_t adf7030_1__SPI_GetBytes (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t Addr, uint32_t nbBytes, uint32_t *pRegVal)
Read "nbBytes" memory location via the SPI.
uint32_t adf7030_1__SPI_GetField (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t Addr, uint32_t Pos, uint32_t Size)
Generic readback of a bitfield value from the Radio PHY via the SPI.
uint16_t adf7030_1__SPI_GetMem16 (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t Addr)
Read a 16bits memory location via the SPI.
uint32_t adf7030_1__SPI_GetMem24 (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t Addr)
Read a 24bits memory location via the SPI.
uint32_t adf7030_1__SPI_GetMem32 (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t Addr)
Read a single 32bits memory location via the SPI.
uint8_t adf7030_1__SPI_GetMem8 (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t Addr)
Read a 8bits memory location via the SPI.
void adf7030_1__SPI_SetBytes (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t Addr, uint32_t Value, uint32_t nbBytes, uint32_t *pRegVal)
Writes "nbBytes" memory location via the SPI.
void adf7030_1__SPI_SetField (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t Addr, uint32_t Pos, uint32_t Size, uint32_t Val)
Generic setting of a Radio PHY bitfield to a value via the SPI.
void adf7030_1__SPI_SetMem16 (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t Addr, uint16_t Value)
Write a single 16bits memory location via the SPI.
void adf7030_1__SPI_SetMem24 (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t Addr, uint32_t Value)
Write a single 24bits memory location via the SPI.
void adf7030_1__SPI_SetMem32 (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t Addr, uint32_t Value)
Write a single 32bits memory location via the SPI.
void adf7030_1__SPI_SetMem8 (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint32_t Addr, uint8_t Value)
Write a single 8bits memory location via the SPI.
ADI_ADF7030_1_RESULT adf7030_1__SPI_Xfer_Mem (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, MEM_DESCRIPTOR_Type *pMEM, bool bREAD_nWRITE)
Generic memory transfers function between Host shadow and the Radio PHY.
ADI_ADF7030_1_RESULT adf7030_1__VerifyConfig (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, MEM_CFG_DESCRIPTOR_Type *pCONFIG)
Function call to verify the integrity of the patch.
ADI_ADF7030_1_RESULT adf7030_1__VerifyDataBlock (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type *pBLOCK)
Function call to verify the integrity of Data block.
ADI_ADF7030_1_RESULT adf7030_1__VerifyPartialDataBlock (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type *pBLOCK, uint16_t Offset, uint16_t Size)
Function call to verify the integrity of a portion of a Host Data block.
ADI_ADF7030_1_RESULT adf7030_1__WriteConfig (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, MEM_CFG_DESCRIPTOR_Type *pCONFIG)
Function call to write Configuration to Radio PHY.
ADI_ADF7030_1_RESULT adf7030_1__WriteDataBlock (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type *pBLOCK)
Function call to write the Data block.
ADI_ADF7030_1_RESULT adf7030_1__WritePartialDataBlock (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type *pBLOCK, uint16_t Offset, uint16_t Size)
Function call to partially write a section of the Host Data block.
ADI_ADF7030_1_RESULT adf7030_1__XferConfig (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, MEM_CFG_DESCRIPTOR_Type *pCONFIG, bool bREAD_nWRITE, bool bCHECK_ONLY)
Generic Configuration transfers function between Host and the Radio PHY.
ADI_ADF7030_1_RESULT adf7030_1__XferDataBlock (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type *pBLOCK, uint16_t Byte_Offset, uint16_t Byte_Size, bool bREAD_nWRITE, bool bCHECK_ONLY)
Generic Data block transfers function between Host and the Radio PHY.
Detailed Description
Macro Definition Documentation
adf7030_1__READ_FIELD
#define adf7030_1__READ_FIELD (fName)
Value:
adf7030_1__SPI_GetField(pSPIDevInfo, \
                                                              fName##_Addr, \
                                                              fName##_Pos, \
                                                              fName##_Size )
Definition at line 309 of file adf7030-1__mem.h.
adf7030_1__READ_REG
#define adf7030_1__READ_REG (rName)
Value:
adf7030_1__SPI_GetBytes(pSPIDevInfo, \
                                                            rName##_Addr, \
                                                            4, \
                                                            NULL )
Definition at line 322 of file adf7030-1__mem.h.
adf7030_1__WRITE_FIELD
#define adf7030_1__WRITE_FIELD (fName, fValue)
Value:
adf7030_1__SPI_SetField(pSPIDevInfo, \
                                                                       fName##_Addr, \
                                                                       fName##_Pos, \
                                                                       fName##_Size, \
                                                                       fValue )
Definition at line 302 of file adf7030-1__mem.h.
adf7030_1__WRITE_REG
#define adf7030_1__WRITE_REG (rName, rValue)
Value:
adf7030_1__SPI_SetBytes(pSPIDevInfo, \
                                                                     rName##_Addr, \
                                                                     rValue, \
                                                                     4, \
                                                                     NULL )
Definition at line 315 of file adf7030-1__mem.h.
Function Documentation
adf7030_1__MEM_CheckByteAccess()
bool adf7030_1__MEM_CheckByteAccess (uint32_t nAddr)
Generic Function to check if byte rw operation is permitted.
Note
By default, all internal memory of the PHY Radio can be accessed at byte level. This includes ROM, RAM and Radio Peripheral Registers. APB Peripherals only support 32bits word access.
Parameters
[in] Addr 32bit byte address location.
Returns
None
Definition at line 1346 of file adf7030-1__mem.c.
Referenced by adf7030_1__SPI_SetField().
adf7030_1__ReadConfig()
ADI_ADF7030_1_RESULT adf7030_1__ReadConfig (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, MEM_CFG_DESCRIPTOR_Type * pCONFIG)
Function call to read Configuration from Radio PHY.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in|out] pCONFIG Pointer to Host configuration structure.
Note
Configuration data is provided by ADI RF Setting Calculator.
See also
USER_CONFIG_20.h for an example. This function modifies SPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the Configuration was readback successfully in the Host.
ADI_ADF7030_1_INVALID_OPERATION If the memory transfer is not allowed.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the Configuration transfert failed.
Definition at line 132 of file adf7030-1__mem.c.
References adf7030_1__XferConfig().
adf7030_1__ReadDataBlock()
ADI_ADF7030_1_RESULT adf7030_1__ReadDataBlock (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type * pBLOCK)
Function call to read the Data block.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pBLOCK Pointer to Host data block structure.
Note
This function modifies SPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the Data block was readback successfully in the Host.
ADI_ADF7030_1_INVALID_OPERATION If the memory transfer is not allowed.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the Data block transfert failed.
Definition at line 286 of file adf7030-1__mem.c.
References adf7030_1__XferDataBlock().
Referenced by adf7030_1__SetupHostPhyCfg().
adf7030_1__ReadPartiaDataBlock()
ADI_ADF7030_1_RESULT adf7030_1__ReadPartiaDataBlock (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type * pBLOCK, uint16_t Offset, uint16_t Size)
Function call to partially read a section of the Host Data block.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pBLOCK Pointer to Host data block structure.
[in] Offset Offset relative to the Host data block structure starting address.
[in] Size Size in byte to be transfered to Host data block structure.
Note
This function modifies SPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the Data block was readback successfully in the Host.
ADI_ADF7030_1_INVALID_OPERATION If the memory transfer is not allowed.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the Data block transfert failed.
Definition at line 386 of file adf7030-1__mem.c.
References adf7030_1__XferDataBlock().
adf7030_1__SPI_GetBytes()
uint32_t adf7030_1__SPI_GetBytes (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t Addr, uint32_t nbBytes, uint32_t * pRegVal)
Read "nbBytes" memory location via the SPI.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] Addr PHY Address location at which the SPI will write.
[in] nbBytes Number of Bytes to read (1, 2, 3 or 4);
[in|out] pRegVal Pointer to full 32bits register writeback location in the event of Addr not being within byte accessible range of the memory map.
Note
This function is changing SPI custom pointer0, pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR] and the PHY SPI pntr are overwritten. It also does not support "SPI Error Status".
Returns
Value 32bits readback value.
See also
adf7030_1__SPI_SetBytes()
Definition at line 1117 of file adf7030-1__mem.c.
References ADI_ADF7030_1_SUCCESS, and adi_adf7030_1_SPI_Info::PHY_PNTR.
Referenced by adf7030_1__SPI_GetField(), adf7030_1__SPI_GetMem16(), adf7030_1__SPI_GetMem24(), adf7030_1__SPI_GetMem32(), adf7030_1__SPI_GetMem8(), and adf7030_1__SPI_SetField().
adf7030_1__SPI_GetField()
uint32_t adf7030_1__SPI_GetField (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t Addr, uint32_t Pos, uint32_t Size)
Generic readback of a bitfield value from the Radio PHY via the SPI.
Note
This function does not support "SPI Error Status". Call adf7030_1__SPI_GetBytes and apply appropriate masking to the SPI value readback.
See also
adf7030_1__SPI_GetBytes().
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] Addr 32bit alligned PHY Address location of the bitfield.
[in] Pos Starting bit position withing the 32bits word.
[in] Size Bit lenght of the bitfield.
Returns
fVal Bitfield value
Definition at line 1306 of file adf7030-1__mem.c.
References adf7030_1__SPI_GetBytes().
Referenced by adf7030_1__Get_PhyPckConfigAddr(), adf7030_1__Get_PhyProfileAddr(), and adf7030_1__GPIO_GetCfg().
adf7030_1__SPI_GetMem16()
uint16_t adf7030_1__SPI_GetMem16 (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t Addr)
Read a 16bits memory location via the SPI.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] Addr PHY Address location at which the SPI will write.
Note
This function is changing SPI custom pointer0, pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR] and the PHY SPI pntr are overwritten. It also does not support "SPI Error Status".
Returns
Value 16bits readback value.
Definition at line 923 of file adf7030-1__mem.c.
References adf7030_1__SPI_GetBytes().
adf7030_1__SPI_GetMem24()
uint32_t adf7030_1__SPI_GetMem24 (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t Addr)
Read a 24bits memory location via the SPI.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] Addr PHY Address location at which the SPI will write.
Note
This function is changing SPI custom pointer0, pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR] and the PHY SPI pntr are overwritten. It also does not support "SPI Error Status".
Returns
Value 24bits readback value.
Definition at line 872 of file adf7030-1__mem.c.
References adf7030_1__SPI_GetBytes().
adf7030_1__SPI_GetMem32()
uint32_t adf7030_1__SPI_GetMem32 (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t Addr)
Read a single 32bits memory location via the SPI.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] Addr PHY Address location at which the SPI will write.
Note
This function does not support "SPI Error Status"
Returns
Value 32bits readback value.
Definition at line 821 of file adf7030-1__mem.c.
References adf7030_1__SPI_GetBytes().
adf7030_1__SPI_GetMem8()
uint8_t adf7030_1__SPI_GetMem8 (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t Addr)
Read a 8bits memory location via the SPI.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] Addr PHY Address location at which the SPI will write.
Note
This function is changing SPI custom pointer0, pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR] and the PHY SPI pntr are overwritten. It also does not support "SPI Error Status".
Returns
Value 8bits readback value.
Definition at line 974 of file adf7030-1__mem.c.
References adf7030_1__SPI_GetBytes().
adf7030_1__SPI_SetBytes()
void adf7030_1__SPI_SetBytes (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t Addr, uint32_t Value, uint32_t nbBytes, uint32_t * pRegVal)
Writes "nbBytes" memory location via the SPI.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] Addr PHY (Byte)Address location at which the SPI will write.
[in] Value Value to write.
[in] nbBytes Number of Bytes to writes (1, 2, 3 or 4);
[in|out] pRegVal Pointer to "last full 32bits value" of Addr location in the event of Addr not being within byte accessible range of the memory map.
Note
This function is changing SPI custom pointer0, pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR] and the PHY SPI pntr are overwritten. It also does not support "SPI Error Status".
Returns
None
See also
adf7030_1__SPI_GetBytes()
Definition at line 1009 of file adf7030-1__mem.c.
References ADI_ADF7030_1_SUCCESS, and adi_adf7030_1_SPI_Info::PHY_PNTR.
Referenced by adf7030_1__IRQ_SetMap(), adf7030_1__SPI_SetField(), adf7030_1__SPI_SetMem16(), adf7030_1__SPI_SetMem24(), adf7030_1__SPI_SetMem32(), and adf7030_1__SPI_SetMem8().
adf7030_1__SPI_SetField()
void adf7030_1__SPI_SetField (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t Addr, uint32_t Pos, uint32_t Size, uint32_t Val)
Generic setting of a Radio PHY bitfield to a value via the SPI.
Note
This function does not support "SPI Error Status". Call adf7030_1__SPI_GetBytes and adf7030_1__SPI_GetBytes and apply appropriate masking to the SPI value readback.
See also
adf7030_1__SPI_GetBytes().
adf7030_1__SPI_SetBytes().
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] Addr 32bit alligned PHY Address location of the bitfield.
[in] Pos Starting bit position withing the 32bits word.
[in] Size Bit lenght of the bitfield.
[in] Val Bitfield value.
Returns
None
Definition at line 1232 of file adf7030-1__mem.c.
References adf7030_1__MEM_CheckByteAccess(), adf7030_1__SPI_GetBytes(), and adf7030_1__SPI_SetBytes().
Referenced by adf7030_1__GPIO_SetCfg(), and adf7030_1__SetupPhyTrigger().
adf7030_1__SPI_SetMem16()
void adf7030_1__SPI_SetMem16 (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t Addr, uint16_t Value)
Write a single 16bits memory location via the SPI.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] Addr PHY Address location at which the SPI will write.
[in] Value 16bits Value to write.
Note
This function is changing SPI custom pointer0, pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR] and the PHY SPI pntr are overwritten. It also does not support "SPI Error Status".
Returns
None
Definition at line 898 of file adf7030-1__mem.c.
References adf7030_1__SPI_SetBytes().
adf7030_1__SPI_SetMem24()
void adf7030_1__SPI_SetMem24 (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t Addr, uint32_t Value)
Write a single 24bits memory location via the SPI.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] Addr PHY Address location at which the SPI will write.
[in] Value 24bits Value to write.
Note
This function is changing SPI custom pointer0, pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR] and the PHY SPI pntr are overwritten. It also does not support "SPI Error Status".
Returns
None
Definition at line 847 of file adf7030-1__mem.c.
References adf7030_1__SPI_SetBytes().
adf7030_1__SPI_SetMem32()
void adf7030_1__SPI_SetMem32 (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t Addr, uint32_t Value)
Write a single 32bits memory location via the SPI.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] Addr PHY Address location at which the SPI will write.
[in] Value 32bits Value to write.
Note
This function does not support "SPI Error Status"
Returns
None
Definition at line 799 of file adf7030-1__mem.c.
References adf7030_1__SPI_SetBytes().
Referenced by adf7030_1__GPIO_ClrPin(), and adf7030_1__GPIO_SetPin().
adf7030_1__SPI_SetMem8()
void adf7030_1__SPI_SetMem8 (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint32_t Addr, uint8_t Value)
Write a single 8bits memory location via the SPI.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] Addr PHY Address location at which the SPI will write.
[in] Value 8bits Value to write.
Note
This function is changing SPI custom pointer0, pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR] and the PHY SPI pntr are overwritten. It also does not support "SPI Error Status".
Returns
None
Definition at line 949 of file adf7030-1__mem.c.
References adf7030_1__SPI_SetBytes().
adf7030_1__SPI_Xfer_Mem()
ADI_ADF7030_1_RESULT adf7030_1__SPI_Xfer_Mem (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, MEM_DESCRIPTOR_Type * pMEM, bool bREAD_nWRITE)
Generic memory transfers function between Host shadow and the Radio PHY.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pMEM Descriptor to the paired Host/PHY memory region.
[in] bREAD_nWRITE Boolean -TRUE to write from Host shadow to the Radio PHY -FALSE to read from Radio PHY back to Host shadow
Note
This function assume the following:
Both Host shadow block (&(pMEM->pBuff)) and PHY memory blocks (pMEM->PhyAddr) are starting at a word alligned location.
pSPIDevInfo->PHY_PNTR[] is in sync with PHY value.
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
Definition at line 641 of file adf7030-1__mem.c.
References adf7030_1__SPI_FindMMapPointer(), MEM_DESCRIPTOR_Type::BlockXfer, BLOCK_XFER_DESCRIPTOR_Type::Offset, MEM_DESCRIPTOR_Type::pBuff, MEM_DESCRIPTOR_Type::PhyAddr, and MEM_DESCRIPTOR_Type::XferMode.
adf7030_1__VerifyConfig()
ADI_ADF7030_1_RESULT adf7030_1__VerifyConfig (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, MEM_CFG_DESCRIPTOR_Type * pCONFIG)
Function call to verify the integrity of the patch.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pCONFIG Pointer to Host configuration structure.
Note
Configuration data is provided by ADI RF Setting Calculator.
See also
USER_CONFIG_20.h for an example. This function modifies SPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the Configuration in the PHY matches the reference in the Host.
ADI_ADF7030_1_INVALID_OPERATION If the memory transfer is not allowed.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the Configuration is different.
Definition at line 162 of file adf7030-1__mem.c.
References adf7030_1__XferConfig().
adf7030_1__VerifyDataBlock()
ADI_ADF7030_1_RESULT adf7030_1__VerifyDataBlock (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type * pBLOCK)
Function call to verify the integrity of Data block.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pBLOCK Pointer to Host data block structure.
Note
This function modifies SPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the Configuration in the PHY matches the reference in the Host.
ADI_ADF7030_1_INVALID_OPERATION If the memory transfer is not allowed.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the Configuration is different.
Definition at line 316 of file adf7030-1__mem.c.
References adf7030_1__XferDataBlock().
adf7030_1__VerifyPartialDataBlock()
ADI_ADF7030_1_RESULT adf7030_1__VerifyPartialDataBlock (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type * pBLOCK, uint16_t Offset, uint16_t Size)
Function call to verify the integrity of a portion of a Host Data block.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pBLOCK Pointer to Host data block structure.
Note
This function modifies SPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the Configuration in the PHY matches the reference in the Host.
ADI_ADF7030_1_INVALID_OPERATION If the memory transfer is not allowed.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the Configuration is different.
Definition at line 418 of file adf7030-1__mem.c.
References adf7030_1__XferDataBlock().
adf7030_1__WriteConfig()
ADI_ADF7030_1_RESULT adf7030_1__WriteConfig (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, MEM_CFG_DESCRIPTOR_Type * pCONFIG)
Function call to write Configuration to Radio PHY.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pCONFIG Pointer to Host configuration structure.
Note
Configuration data is provided by ADI RF Setting Calculator.
See also
USER_CONFIG_20.h for an example. This function modifies SPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the Configuration was written successfully in the Host.
ADI_ADF7030_1_INVALID_OPERATION If the memory transfer is not allowed.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the Configuration transfert failed.
Definition at line 102 of file adf7030-1__mem.c.
References adf7030_1__XferConfig().
adf7030_1__WriteDataBlock()
ADI_ADF7030_1_RESULT adf7030_1__WriteDataBlock (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type * pBLOCK)
Function call to write the Data block.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pBLOCK Pointer to Host data block structure.
Note
This function modifies SPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the Data block was written successfully in the Host.
ADI_ADF7030_1_INVALID_OPERATION If the memory transfer is not allowed.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the Data block transfert failed.
Definition at line 256 of file adf7030-1__mem.c.
References adf7030_1__XferDataBlock().
adf7030_1__WritePartialDataBlock()
ADI_ADF7030_1_RESULT adf7030_1__WritePartialDataBlock (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type * pBLOCK, uint16_t Offset, uint16_t Size)
Function call to partially write a section of the Host Data block.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pBLOCK Pointer to Host data block structure.
[in] Offset Offset relative to the Host data block structure starting address.
[in] Size Size in byte to be transfered from Host data block structure.
Note
This function modifies SPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the Data block was written successfully in the Host.
ADI_ADF7030_1_INVALID_OPERATION If the memory transfer is not allowed.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the Data block transfert failed.
Definition at line 350 of file adf7030-1__mem.c.
References adf7030_1__XferDataBlock().
adf7030_1__XferConfig()
ADI_ADF7030_1_RESULT adf7030_1__XferConfig (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, MEM_CFG_DESCRIPTOR_Type * pCONFIG, bool bREAD_nWRITE, bool bCHECK_ONLY)
Generic Configuration transfers function between Host and the Radio PHY.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pCONFIG Pointer to Host configuration structure.
[in] bREAD_nWRITE Boolean -TRUE to write Config from Host to the Radio PHY -FALSE to read Config from Radio PHY back to Host
[in] bCHECK_ONLY Boolean -TRUE to check PHY Config versus Host Reference -FALSE [D] to perform READ_nWRITE operation
Note
This function can modify pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfert was succesfull to the adf7030-1.
ADI_ADF7030_1_INVALID_OPERATION If the memory transfer is not allowed.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfert failed.
Definition at line 196 of file adf7030-1__mem.c.
References adf7030_1__XferDataBlock(), ADI_ADF7030_1_SPI_COMM_FAILED, ADI_ADF7030_1_SUCCESS, MEM_CFG_DESCRIPTOR_Type::BLOCKS, MEM_CFG_DESCRIPTOR_Type::nbBlock, and MEM_CFG_DESCRIPTOR_Type::pNext.
Referenced by adf7030_1__ReadConfig(), adf7030_1__VerifyConfig(), and adf7030_1__WriteConfig().
adf7030_1__XferDataBlock()
ADI_ADF7030_1_RESULT adf7030_1__XferDataBlock (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, DATA_BLOCK_DESCRIPTOR_Type * pBLOCK, uint16_t Byte_Offset, uint16_t Byte_Size, bool bREAD_nWRITE, bool bCHECK_ONLY)
Generic Data block transfers function between Host and the Radio PHY.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pBLOCK Pointer to Host configuration structure sub data block.
[in] Offset Offset relative to the Host data block structure starting address.
[in] Size Size in byte to be transfered from Host data block structure.
[in] bREAD_nWRITE Boolean -TRUE to write data block from Host to the Radio PHY -FALSE to read data block from Radio PHY back to Host
[in] bCHECK_ONLY Boolean -TRUE to check PHY data block versus Host Reference -FALSE [D] to perform READ_nWRITE operation
Note
This function can modify pSPIDevInfo->PHY_PNTR[PNTR_CUSTOM0_ADDR].
Returns
Status
ADI_ADF7030_1_SUCCESS If the transfer was successful to the adf7030-1.
ADI_ADF7030_1_INVALID_OPERATION If the memory transfer is not allowed
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the transfer failed.
Definition at line 460 of file adf7030-1__mem.c.
References DATA_BLOCK_DESCRIPTOR_Type::Addr, adf7030_1__SPI_FindMMapPointer(), adf7030_1__SPI_rd_cmp_byte_p_a(), adf7030_1__SPI_SetMMapCustomPntr0(), ADI_ADF7030_1_SPI_COMM_FAILED, ADI_ADF7030_1_SUCCESS, DATA_BLOCK_DESCRIPTOR_Type::pData, and DATA_BLOCK_DESCRIPTOR_Type::WordXfer.
Referenced by adf7030_1__ReadDataBlock(), adf7030_1__ReadPartiaDataBlock(), adf7030_1__VerifyDataBlock(), adf7030_1__VerifyPartialDataBlock(), adf7030_1__WriteDataBlock(), adf7030_1__WritePartialDataBlock(), and adf7030_1__XferConfig().