ADF7030-1 Device Drivers API Reference Manual: Interrupt Interface
Interrupt Interface
ADF7030-1 Driver
Macros
#define adf7030_1__IRQ_ClrAllStatus(pDevInfo, eIntPin) adf7030_1__IRQ_ClrStatus(pDevInfo, eIntPin, 0xFFFFFFFF)
Enumerations
enum ADI_AF7030_1_EXT_IRQn_Msk_Type {
PREAMBLE_IRQn_Msk = (1UL << PREAMBLE_IRQn),
PREAMBLE_GONE_IRQn_Msk = (1UL << PREAMBLE_GONE_IRQn),
SYNCWORD_IRQn_Msk = (1UL << SYNCWORD_IRQn),
LENGTH_IRQn_Msk = (1UL << LENGTH_IRQn),
PAYLOAD_IRQn_Msk = (1UL << PAYLOAD_IRQn),
PAYLOAD_BLOC_IRQn_Msk = (1UL << PAYLOAD_BLOC_IRQn),
CRC_CHK_IRQn_Msk = (1UL << CRC_CHK_IRQn),
EOF_IRQn_Msk = (1UL << EOF_IRQn),
BUFF_HALF_IRQn_Msk = (1UL << BUFF_HALF_IRQn),
BUFF_FULL_IRQn_Msk = (1UL << BUFF_FULL_IRQn),
SM_READY_IRQn_Msk = (1UL << SM_READY_IRQn),
SM_IDLE_IRQn_Msk = (1UL << SM_IDLE_IRQn),
SM_BODY_IRQn_Msk = (1UL << SM_BODY_IRQn),
SM_SCRIPT_IRQn_Msk = (1UL << SM_SCRIPT_IRQn),
SM_ERROR_IRQn_Msk = (1UL << SM_ERROR_IRQn),
SNOOP_IRQn_Msk = (1UL << SNOOP_IRQn),
HARDFAULT_IRQn_Msk = (1UL << HARDFAULT_IRQn),
SPI_HOST_EXT_IRQn_Msk = (1UL << SPI_HOST_EXT_IRQn),
TMR0_EXT_IRQn_Msk = (1UL << TMR0_EXT_IRQn),
TMR1_EXT_IRQn_Msk = (1UL << TMR1_EXT_IRQn),
TMR2_EXT_IRQn_Msk = (1UL << TMR2_EXT_IRQn),
TMR3_EXT_IRQn_Msk = (1UL << TMR3_EXT_IRQn),
UNUSED0_IRQn_Msk = (1UL << UNUSED0_IRQn),
RTC_EXT_IRQn_Msk = (1UL << RTC_EXT_IRQn),
WDT_EXT_IRQn_Msk = (1UL << WDT_EXT_IRQn),
SERDES_EXT_IRQn_Msk = (1UL << SERDES_EXT_IRQn),
SERDES_MONITOR_EXT_IRQn_Msk = (1UL <<SERDES_MONITOR_EXT_IRQn),
MCR_SNOOP_EXT_IRQn_Msk = (1UL << MCR_SNOOP_EXT_IRQn),
CAL_READY_EXT_IRQn_Msk = (1UL << CAL_READY_EXT_IRQn),
AGC_EXT_IRQn_Msk = (1UL << AGC_EXT_IRQn),
UNUSED1_IRQn_Msk = (1UL << UNUSED1_IRQn),
UNUSED2_IRQn_Msk = (1UL << UNUSED2_IRQn),
UNUSED3_IRQn_Msk = (1UL << UNUSED3_IRQn)
}
enum ADI_AF7030_1_EXT_IRQn_Type {
PREAMBLE_IRQn = 0UL,
PREAMBLE_GONE_IRQn = 1UL,
SYNCWORD_IRQn = 2UL,
LENGTH_IRQn = 3UL,
PAYLOAD_IRQn = 4UL,
PAYLOAD_BLOC_IRQn = 5UL,
CRC_CHK_IRQn = 6UL,
EOF_IRQn = 7UL,
BUFF_HALF_IRQn = 8UL,
BUFF_FULL_IRQn = 9UL,
SM_READY_IRQn = 10UL,
SM_IDLE_IRQn = 11UL,
SM_BODY_IRQn = 12UL,
SM_SCRIPT_IRQn = 13UL,
SM_ERROR_IRQn = 13UL,
SNOOP_IRQn = 14UL,
HARDFAULT_IRQn = 15UL,
SPI_HOST_EXT_IRQn = 16UL,
TMR0_EXT_IRQn = 17UL,
TMR1_EXT_IRQn = 18UL,
TMR2_EXT_IRQn = 19UL,
TMR3_EXT_IRQn = 20UL,
UNUSED0_IRQn = 21UL,
RTC_EXT_IRQn = 22UL,
WDT_EXT_IRQn = 23UL,
SERDES_EXT_IRQn = 24UL,
SERDES_MONITOR_EXT_IRQn = 25UL,
MCR_SNOOP_EXT_IRQn = 26UL,
CAL_READY_EXT_IRQn = 27UL,
AGC_EXT_IRQn = 28UL,
UNUSED1_IRQn = 29UL,
UNUSED2_IRQn = 30UL,
UNUSED3_IRQn = 31UL
}
Functions
void adf7030_1__IRQ_Callback (void *pCBParam, uint32_t Port, void *PinIntData)
Default gpio driver Callback function for interrupt pin 0.
ADI_ADF7030_1_RESULT adf7030_1__IRQ_ClrStatus (ADI_ADF7030_1_INFO *pDevInfo, ADI_ADF7030_1_INTPIN eIntPin, uint32_t nIntClear)
Clear the PHY eIntPin interrupt pin.
ADI_ADF7030_1_RESULT adf7030_1__IRQ_ConfigHostIntPin (ADI_ADF7030_1_HANDLE const hDevice, IRQn_Type eIrq, ADI_ADF7030_1_INTPIN eIntPin, ADI_GPIO_PORT eGPIOPort, ADI_GPIO_DATA nGPIOPin)
Sets the processor GPIO pin to which the ADF7030-1 interrupt pin is connected.
ADI_ADF7030_1_RESULT adf7030_1__IRQ_GetClrStatus (ADI_ADF7030_1_INFO *pDevInfo, ADI_ADF7030_1_INTPIN eIntPin)
Readback and Clear the PHY eIntPin interrupt pin.
ADI_ADF7030_1_RESULT adf7030_1__IRQ_GetMap (ADI_ADF7030_1_INFO *pDevInfo, ADI_ADF7030_1_INTPIN eIntPin)
Readbacks the PHY interrupt source mask register.
ADI_ADF7030_1_RESULT adf7030_1__IRQ_GetStatus (ADI_ADF7030_1_INFO *pDevInfo, ADI_ADF7030_1_INTPIN eIntPin)
Readbacks the PHY interrupt status register.
ADI_ADF7030_1_RESULT adf7030_1__IRQ_Init (ADI_ADF7030_1_HANDLE const hDevice)
Initializes Irq handling for the adf7030-1 PHY.
ADI_ADF7030_1_RESULT adf7030_1__IRQ_SetCallback (ADI_ADF7030_1_INFO *pDevInfo, ADI_ADF7030_1_INTPIN eIntPin, ADI_CALLBACK pfCallback)
Changes GPIO Callback on PHY interrupt.
ADI_ADF7030_1_RESULT adf7030_1__IRQ_SetGPIOPin (ADI_ADF7030_1_INFO *pDevInfo, ADI_ADF7030_1_INTPIN eIntPin)
Setup PHY Radio GPIO irq.
ADI_ADF7030_1_RESULT adf7030_1__IRQ_SetMap (ADI_ADF7030_1_INFO *pDevInfo, ADI_ADF7030_1_INTPIN eIntPin, uint32_t nIntMap)
Configures the PHY interrupt source mask register.
ADI_ADF7030_1_RESULT adf7030_1__IRQ_SetupHostGPIO (ADI_ADF7030_1_INFO *pDevInfo, ADI_ADF7030_1_INTPIN eIntPin, ADI_CALLBACK pfCallback, ADI_GPIO_IRQ_TRIGGER_CONDITION eSense)
Setup the Host GPIO driver to trigger Callback on PHY interrupt.
ADI_ADF7030_1_RESULT adf7030_1__IRQ_UnInit (ADI_ADF7030_1_HANDLE const hDevice)
Unitializes Irq handling for the adf7030-1 PHY.
Variables
uint8_t GPIOCallbackMem [ADI_GPIO_MEMORY_SIZE]
Detailed Description
Enumeration Type Documentation
ADI_AF7030_1_EXT_IRQn_Type
enum ADI_AF7030_1_EXT_IRQn_Type
Enumerator
PREAMBLE_IRQn
0 Preamble detected (RX) / Start preamble (TX)
PREAMBLE_GONE_IRQn
1 Preamble gone (RX) / End of preamble (TX)
SYNCWORD_IRQn
2 Syncword detected (RX) / End of Syncword (TX)
LENGTH_IRQn
3 Valid Length received (RX) / End of Length word (TX)
PAYLOAD_IRQn
4 Full payload received (RX) / Full payload transmitted (TX)
PAYLOAD_BLOC_IRQn
5 TRX bloc received (RX) / TRX bloc transmitted (TX)
CRC_CHK_IRQn
6 Frame CRC correct (RX) / Frame CRC transmitted (TX)
EOF_IRQn
7 End of Frame (RX) / End od Frame (TX)
BUFF_HALF_IRQn
8 Rolling Buffer Half Full
BUFF_FULL_IRQn
9 Rolling Buffer Full
SM_READY_IRQn
10 State Machine ready for new command
SM_IDLE_IRQn
11 State Machine in idle
SM_BODY_IRQn
12 State Machine in state body function
SM_SCRIPT_IRQn
13 State Machine end of script
SM_ERROR_IRQn
13 State Machine error
SNOOP_IRQn
14 MCR Snoop IRQ
HARDFAULT_IRQn
15 Critical firmware error
SPI_HOST_EXT_IRQn
16
TMR0_EXT_IRQn
17
TMR1_EXT_IRQn
18
TMR2_EXT_IRQn
19
TMR3_EXT_IRQn
20
UNUSED0_IRQn
21
RTC_EXT_IRQn
22
WDT_EXT_IRQn
23
SERDES_EXT_IRQn
24
SERDES_MONITOR_EXT_IRQn
25
MCR_SNOOP_EXT_IRQn
26
CAL_READY_EXT_IRQn
27
AGC_EXT_IRQn
28
UNUSED1_IRQn
29
UNUSED2_IRQn
30
UNUSED3_IRQn
31
Definition at line 69 of file adf7030-1__irq.h.
Function Documentation
adf7030_1__IRQ_Callback()
void adf7030_1__IRQ_Callback (void * pCBParam, uint32_t Port, void * PinIntData)
Default gpio driver Callback function for interrupt pin 0.
Note
This function is getting call on detecting a rising edge of the ADI_ADF7030_1_INTPIN0 or ADI_ADF7030_1_INTPIN1 interrupt pin of the PHY Radio.
Parameters
[in] pCBParam Callback parameter passed to the radio driver application (Pointer to Device Instance data structure information)
[in] Port Host GPIO service port source (ADI_GPIO_EVENT) calling the callback
[in] PinIntData Pointer to the Host GPIO pin interrupt data source (ADI_GPIO_DATA)
Returns
None
Definition at line 113 of file adf7030-1__irq.c.
References ADI_ADF7030_1_EVENT_INT0, ADI_ADF7030_1_EVENT_INT1, ADI_ADF7030_1_INTPIN0, ADI_ADF7030_1_INTPIN1, adi_adf7030_1_GPIO_Int_info::ePort, adi_adf7030_1_info::IntGPIOInfo, adi_adf7030_1_GPIO_Int_info::nPin, and adi_adf7030_1_info::pfCallback.
Referenced by adf7030_1__IRQ_Init().
adf7030_1__IRQ_ClrStatus()
ADI_ADF7030_1_RESULT adf7030_1__IRQ_ClrStatus (ADI_ADF7030_1_INFO * pDevInfo, ADI_ADF7030_1_INTPIN eIntPin, uint32_t nIntClear)
Clear the PHY eIntPin interrupt pin.
Note
This function clears the Radio PHY interrupt status register by "write one to clear" operation. If PHY status register is 0, external GPIO line will be deasserted. See all available interrupt sources ADI_AF7030_1_EXT_IRQn_Type.
Parameters
[in] pDevInfo Pointer to the ADF7030-1 instance information structure.
[in] eIntPin Interrupt id (ADI_ADF7030_1_INTPIN) to configure.
[in] nIntClear Interrupt events to clear.
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY intance irq status was succesfully cleared
ADI_ADF7030_1_SPI_COMM_FAILED [D] PHY irq status clearing failed
Definition at line 579 of file adf7030-1__irq.c.
References adf7030_1__SPI_wr_word_b_a(), ADI_ADF7030_1_SUCCESS, adi_adf7030_1_info::IntGPIOInfo, IRQ_CTRL_STATUS0_Addr, adi_adf7030_1_GPIO_Int_info::nIntStatus, and adi_adf7030_1_info::SPIInfo.
adf7030_1__IRQ_ConfigHostIntPin()
ADI_ADF7030_1_RESULT adf7030_1__IRQ_ConfigHostIntPin (ADI_ADF7030_1_HANDLE const hDevice, IRQn_Type eIrq, ADI_ADF7030_1_INTPIN eIntPin, ADI_GPIO_PORT eGPIOPort, ADI_GPIO_DATA nGPIOPin)
Sets the processor GPIO pin to which the ADF7030-1 interrupt pin is connected.
ADF7030-1 has two interrupt pins (INT0 and INT1) which can be connected to the host processor for notifying the events. Depending upon the board design, the ADF7030-1 interrupt pins can be connected to different GPIO pins on the host processor. This API can be used to specify the GPIO pin for which each of the interrupt is connected. This API should be called separately (can be twice) to specify the GPIO pin for each of the ADF7030-1 interrupt pins.
Note
This function should not be called after data flow is enabled.
Parameters
[in] hDevice Handle to ADF7030-1 device whose interrupt pin to be configured.
[in] eIrq Indicate whether the interrupt need to be mapped to GROUP-A OR to GROUP-B.
[in] eIntPin ADF7030-1 interrupt pin to be configured.
[in] eGPIOPort GPIO port of the host processor to which the given ADF7030-1 interrupt pin is connected.
[in] nGPIOPin GPIO pin within the given port to which the given ADF7030-1 interrupt pin is connected.
Returns
Status
ADI_ADF7030_1_SUCCESS If successfully mapped GPIO pin for interrupt pin.
ADI_ADF7030_1_INVALID_HANDLE [D] If the given ADF7030-1 device handle is invalid.
ADI_ADF7030_1_DEVICE_NOT_OPENED [D] If the given device is not yet opened.
ADI_ADF7030_1_INVALID_OPERATION [D] If trying to configure GPIO pin for an interrupt after measurement is enabled.
Definition at line 322 of file adf7030-1__irq.c.
References ADI_ADF7030_1_INVALID_OPERATION, ADI_ADF7030_1_STATE_CONFIGURED, ADI_ADF7030_1_SUCCESS, adi_adf7030_1_GPIO_Int_info::eIRQType, adi_adf7030_1_GPIO_Int_info::ePort, adi_adf7030_1_device::eState, adi_adf7030_1_info::IntGPIOInfo, adi_adf7030_1_GPIO_Int_info::nPin, and adi_adf7030_1_device::pDevInfo.
adf7030_1__IRQ_GetClrStatus()
ADI_ADF7030_1_RESULT adf7030_1__IRQ_GetClrStatus (ADI_ADF7030_1_INFO * pDevInfo, ADI_ADF7030_1_INTPIN eIntPin)
Readback and Clear the PHY eIntPin interrupt pin.
Note
This function readback the Radio PHY interrupt status register and use the value immadiately clear by "write one to clear" operation. If PHY status register is 0, external GPIO line will be deasserted. In this case, pGPIOInfo->nIntStatus holds the state of the PHY status register pior to clearing it. See all available interrupt sources ADI_AF7030_1_EXT_IRQn_Type.
Parameters
[in] pDevInfo Pointer to the ADF7030-1 instance information structure.
[in] eIntPin Interrupt id (ADI_ADF7030_1_INTPIN) to configure.
[in] nIntClear Interrupt events to clear.
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY intance irq status was succesfully readback and cleared
ADI_ADF7030_1_SPI_COMM_FAILED [D] PHY irq status reading or clearing failed
Definition at line 626 of file adf7030-1__irq.c.
References adi_adf7030_1_info::IntGPIOInfo.
adf7030_1__IRQ_GetMap()
ADI_ADF7030_1_RESULT adf7030_1__IRQ_GetMap (ADI_ADF7030_1_INFO * pDevInfo, ADI_ADF7030_1_INTPIN eIntPin)
Readbacks the PHY interrupt source mask register.
Note
This function transfers the Radio PHY interrupt mask resgister back into the Host interrupt pin configuration structure. See all available interrupt sources ADI_AF7030_1_EXT_IRQn_Type.
Parameters
[in] pDevInfo Pointer to the ADF7030-1 instance information structure.
[in] eIntPin Interrupt id (ADI_ADF7030_1_INTPIN) to configure.
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY intance irq mask was succesfully readback
ADI_ADF7030_1_SPI_COMM_FAILED [D] PHY irq mask readback failed
Definition at line 502 of file adf7030-1__irq.c.
References adi_adf7030_1_info::IntGPIOInfo.
adf7030_1__IRQ_GetStatus()
ADI_ADF7030_1_RESULT adf7030_1__IRQ_GetStatus (ADI_ADF7030_1_INFO * pDevInfo, ADI_ADF7030_1_INTPIN eIntPin)
Readbacks the PHY interrupt status register.
Note
This function readback the Radio PHY interrupt status register back into the Host interrupt pin configuration structure. See all available interrupt sources ADI_AF7030_1_EXT_IRQn_Type.
Parameters
[in] pDevInfo Pointer to the ADF7030-1 instance information structure.
[in] eIntPin Interrupt id (ADI_ADF7030_1_INTPIN) to configure.
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY intance irq status was succesfully readback
ADI_ADF7030_1_SPI_COMM_FAILED [D] PHY irq status readback failed
Definition at line 544 of file adf7030-1__irq.c.
References adi_adf7030_1_info::IntGPIOInfo.
adf7030_1__IRQ_Init()
ADI_ADF7030_1_RESULT adf7030_1__IRQ_Init (ADI_ADF7030_1_HANDLE const hDevice)
Initializes Irq handling for the adf7030-1 PHY.
Note
This function open the GPIO service, configure the Host GPIO according to the pDevInfo->IntGPIOInfo and setup callbacks events. If the GPIO interface is changing at runtime, user can call the adf7030_1__IRQ_ConfigIntPin() followed by adf7030_1__IRQ_Init().
Parameters
[in] hDevice Handle to ADF3030-1 device instance.
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY intance was succesfully initialized
ADI_ADF7030_1_GPIO_DEV_FAILED [D] PHY initialisation failed
See also
adf7030_1__SPI_UnInit().
Definition at line 169 of file adf7030-1__irq.c.
References adf7030_1__IRQ_Callback(), adf7030_1__IRQ_SetupHostGPIO(), ADI_ADF7030_1_GPIO_DEV_FAILED, ADI_ADF7030_1_INTPIN0, ADI_ADF7030_1_INTPIN1, ADI_ADF7030_1_SUCCESS, GPIOCallbackMem, and adi_adf7030_1_device::pDevInfo.
Referenced by adf7030_1__Setup().
adf7030_1__IRQ_SetCallback()
ADI_ADF7030_1_RESULT adf7030_1__IRQ_SetCallback (ADI_ADF7030_1_INFO * pDevInfo, ADI_ADF7030_1_INTPIN eIntPin, ADI_CALLBACK pfCallback)
Changes GPIO Callback on PHY interrupt.
Note
User can use this function in case default Irq callback does not suite the application needs.
Parameters
[in] pDevInfo Pointer to the ADF7030-1 instance information structure.
[in] eIntPin Interrupt id (ADI_ADF7030_1_INTPIN) to configure.
[in] pfCallback Callback function which will be called upon interrupt detection.
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY intance irq callback was succesfully configured
ADI_ADF7030_1_GPIO_DEV_FAILED [D] PHY callback configuration failed
Definition at line 670 of file adf7030-1__irq.c.
References ADI_ADF7030_1_GPIO_DEV_FAILED, ADI_ADF7030_1_SUCCESS, adi_adf7030_1_GPIO_Int_info::eIRQType, adi_adf7030_1_info::IntGPIOInfo, and adi_adf7030_1_GPIO_Int_info::pfCallback.
Referenced by adf7030_1__IRQ_SetupHostGPIO(), and adf7030_1__IRQ_UnInit().
adf7030_1__IRQ_SetGPIOPin()
ADI_ADF7030_1_RESULT adf7030_1__IRQ_SetGPIOPin (ADI_ADF7030_1_INFO * pDevInfo, ADI_ADF7030_1_INTPIN eIntPin)
Setup PHY Radio GPIO irq.
Note
User can use this function prior to issuing CFG_DEV command to configure the PHY Radio pinmux setting for each individual IRQ pin.
Parameters
[in] pDevInfo Pointer to the ADF7030-1 instance information structure.
[in] eIntPin Interrupt id (ADI_ADF7030_1_INTPIN) to configure.
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY irq GPIO was configured
ADI_ADF7030_1_SPI_COMM_FAILED [D] PHY irq GPIO configuration failed
Definition at line 708 of file adf7030-1__irq.c.
References adf7030_1__GPIO_SetCfg(), ADI_ADF7030_1_INTPIN1, adi_adf7030_1_GPIO_Int_info::ePhyPin, adi_adf7030_1_SPI_Info::eXferResult, GPIO_IRQ_OUT0, GPIO_IRQ_OUT1, adi_adf7030_1_info::IntGPIOInfo, and adi_adf7030_1_info::SPIInfo.
adf7030_1__IRQ_SetMap()
ADI_ADF7030_1_RESULT adf7030_1__IRQ_SetMap (ADI_ADF7030_1_INFO * pDevInfo, ADI_ADF7030_1_INTPIN eIntPin, uint32_t nIntMap)
Configures the PHY interrupt source mask register.
Note
This function transfers bit [31:8] of nIntMap into the Radio PHY interrupt mask resgister. Lower bits [7:0] are written into the PHY profile packet interrupt location. See all available interrupt sources ADI_AF7030_1_EXT_IRQn_Type.
Parameters
[in] pDevInfo Pointer to the ADF7030-1 instance information structure.
[in] eIntPin Interrupt id (ADI_ADF7030_1_INTPIN) to configure.
[in] nIntMap Interrupt events which will be triggering PHY irq line.
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY intance irq mask was succesfully configured
ADI_ADF7030_1_SPI_COMM_FAILED [D] PHY irq mask configuration failed
Definition at line 452 of file adf7030-1__irq.c.
References adf7030_1__SPI_SetBytes(), adf7030_1__SPI_wr_word_b_a(), ADI_ADF7030_1_SPI_COMM_FAILED, ADI_ADF7030_1_SUCCESS, adi_adf7030_1_SPI_Info::eXferResult, GENERIC_PKT_FRAME_CFG1_Addr, adi_adf7030_1_info::IntGPIOInfo, IRQ_CTRL_MASK0_Addr, adi_adf7030_1_GPIO_Int_info::nIntMap, and adi_adf7030_1_info::SPIInfo.
adf7030_1__IRQ_SetupHostGPIO()
ADI_ADF7030_1_RESULT adf7030_1__IRQ_SetupHostGPIO (ADI_ADF7030_1_INFO * pDevInfo, ADI_ADF7030_1_INTPIN eIntPin, ADI_CALLBACK pfCallback, ADI_GPIO_IRQ_TRIGGER_CONDITION eSense)
Setup the Host GPIO driver to trigger Callback on PHY interrupt.
Note
This function remove IRQ callbacks and disable IRQs on the PHY
Parameters
[in] pDevInfo Pointer to the ADF7030-1 instance information structure.
[in] eIntPin Interrupt id (ADI_ADF7030_1_INTPIN) to configure.
[in] pfCallback Callback function which will be called upon interrupt detection.
[in] eSense Trigger condition for GPIO interrupt.
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY intance was succesfully configured
ADI_ADF7030_1_GPIO_DEV_FAILED [D] PHY configuration failed
Definition at line 386 of file adf7030-1__irq.c.
References adf7030_1__IRQ_SetCallback(), ADI_ADF7030_1_GPIO_DEV_FAILED, ADI_ADF7030_1_SUCCESS, adi_adf7030_1_GPIO_Int_info::eIRQType, adi_adf7030_1_GPIO_Int_info::ePort, adi_adf7030_1_info::IntGPIOInfo, and adi_adf7030_1_GPIO_Int_info::nPin.
Referenced by adf7030_1__IRQ_Init().
adf7030_1__IRQ_UnInit()
ADI_ADF7030_1_RESULT adf7030_1__IRQ_UnInit (ADI_ADF7030_1_HANDLE const hDevice)
Unitializes Irq handling for the adf7030-1 PHY.
Note
This function remove IRQ callbacks and disable IRQs on the PHY
Parameters
[in] hDevice Handle to ADF3030-1 device instance.
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY intance was succesfully uninitialized
ADI_ADF7030_1_GPIO_DEV_FAILED [D] PHY uninitialisation failed
See also
adf7030_1__SPI_Init().
Definition at line 242 of file adf7030-1__irq.c.
References adf7030_1__IRQ_SetCallback(), ADI_ADF7030_1_GPIO_DEV_FAILED, ADI_ADF7030_1_INTPIN0, ADI_ADF7030_1_INTPIN1, ADI_ADF7030_1_SUCCESS, and adi_adf7030_1_device::pDevInfo.
Referenced by adf7030_1__Close().
Variable Documentation
GPIOCallbackMem
uint8_t GPIOCallbackMem[ADI_GPIO_MEMORY_SIZE]
Memory required for underlying GPIO callbacks (service)
Memory required for GPIO service
Definition at line 186 of file adf703x_tx_test_modes.c.
Referenced by adf7030_1__IRQ_Init().