ADF7030-1 Device Drivers API Reference Manual: Core Interface
Core Interface
ADF7030-1 Driver
Macros
#define ADI_ADF7030_1_MEMORY_SIZE (sizeof(ADI_ADF7030_1_INFO))
Functions
ADI_ADF7030_1_RESULT adf7030_1__Close (ADI_ADF7030_1_HANDLE const hDevice)
Closes the adf7030-1 instance.
ADI_ADF7030_1_RESULT adf7030_1__Enable (ADI_ADF7030_1_HANDLE const hDevice, bool bEnable)
Enable the adf7030-1.
ADI_ADF7030_1_RESULT adf7030_1__EnableHostTrigger (ADI_ADF7030_1_INFO *pDevInfo, ADI_ADF7030_1_TRIGPIN eTRIG, bool bEnable)
Initialise the Host GPIO Trigger pin to interface with the PHY Radio.
ADI_ADF7030_1_RESULT adf7030_1__EnablePhyTrigger (ADI_ADF7030_1_INFO *pDevInfo, ADI_ADF7030_1_RADIO_EXTENDED ExCmd)
ADI_ADF7030_1_RESULT adf7030_1__Get_PhyPckConfigAddr (ADI_ADF7030_1_INFO *pDevInfo, uint32_t *pAddr)
Readback the PHY Packet configuration location.
ADI_ADF7030_1_RESULT adf7030_1__Get_PhyProfileAddr (ADI_ADF7030_1_INFO *pDevInfo, uint32_t *pAddr)
Readback the PHY Radio profile location.
ADI_ADF7030_1_RESULT adf7030_1__Open (uint32_t nDeviceNum, void *const pDeviceMemory, uint32_t nMemSize, ADI_CALLBACK pfCallback, void *const pCBParam, ADI_ADF7030_1_HANDLE *const phDevice)
Opens the adf7030-1 driver.
ADI_ADF7030_1_RESULT adf7030_1__PulseReset (ADI_ADF7030_1_INFO *pDevInfo)
Pulse Host GPIO Reset pin.
ADI_ADF7030_1_RESULT adf7030_1__PulseTrigger (ADI_ADF7030_1_INFO *pDevInfo, ADI_ADF7030_1_TRIGPIN eTRIG)
Pulse Host GPIO Trigger pin.
ADI_ADF7030_1_RESULT adf7030_1__Set_PhyPckConfigAddr (ADI_ADF7030_1_INFO *pDevInfo, uint32_t Addr)
Set the PHY Packet configuration location.
ADI_ADF7030_1_RESULT adf7030_1__Set_PhyProfileAddr (ADI_ADF7030_1_INFO *pDevInfo, uint32_t Addr)
Set the PHY Radio profile location.
ADI_ADF7030_1_RESULT adf7030_1__Setup (ADI_ADF7030_1_HANDLE const hDevice, ADI_ADF7030_1_SPI_INFO *const pSPIDevInfo, ADI_ADF7030_1_GPIO_INT_INFO *const pINTDevInfo, ADI_ADF7030_1_GPIO_TRIG_INFO *const pTRIGDevInfo, ADI_ADF7030_1_GPIO_RESET_INFO *const pRESETDevInfo)
Setup the adf7030-1 instance by initialising its device info structure. It also calls adf7030_1__SPI_Init() and adf7030_1__IRQ_Init() to setup underlying SPI driver and GPIO service.
ADI_ADF7030_1_RESULT adf7030_1__SetupHostPhyCfg (ADI_ADF7030_1_HANDLE const hDevice, void *const pCfgMem, uint32_t nCfgMemSize, MEM_CFG_DESCRIPTOR_Type *pCfgRef, bool bInit)
Initialise the Host shadow configuration of the PHY Radio.
ADI_ADF7030_1_RESULT adf7030_1__SetupHostTrxBuffer (ADI_ADF7030_1_INFO *pDevInfo, void *const pTrxMem, uint32_t nTrxMemSize)
Initialise the Host shadow TRX payload buffer of the PHY Radio.
ADI_ADF7030_1_RESULT adf7030_1__SetupPhyTrigger (ADI_ADF7030_1_INFO *pDevInfo, ADI_ADF7030_1_TRIGPIN eTRIG, ADI_ADF7030_1_RADIO_STATE goState)
Setup PHY gpio to for external trigger command.
Variables
ADI_ADF7030_1_DEVICE gADF7030_1_Dev [ADF7030_1_NUM_INSTANCES]
Detailed Description
Macro Definition Documentation
ADI_ADF7030_1_MEMORY_SIZE
#define ADI_ADF7030_1_MEMORY_SIZE (sizeof(ADI_ADF7030_1_INFO))
Memory required by the ADF7030_1 driver including the memory required for its dependent drivers
Definition at line 51 of file adf7030-1__core.h.
Function Documentation
adf7030_1__Close()
ADI_ADF7030_1_RESULT adf7030_1__Close (ADI_ADF7030_1_HANDLE const hDevice)
Closes the adf7030-1 instance.
This function stops any PHY Radio operation, and closes the device, this puts the ADF7030-1 into phy_off mode.
Parameters
[in] hDevice Handle to ADF7030-1 device instance to be closed.
Returns
Status
ADI_ADF7030_1_SUCCESS If successfully closed the ADF7030-1 device.
ADI_ADF7030_1_INVALID_HANDLE [D] If the given ADF7030-1 device handle is invalid.
ADI_ADF7030_1_DEVICE_NOT_OPENED [D] if the given device is not yet opened.
ADI_ADF7030_1_SPI_DEV_FAILED Failed to terminate GPIO service.
ADI_ADF7030_1_GPIO_DEV_FAILED Failed to terminate SPI driver.
ADI_ADF7030_1_FAILURE Failed to disable Radio PHY instance.
See also
adf7030_1__Open()
Definition at line 956 of file adf7030-1__core.c.
References adf7030_1__Enable(), adf7030_1__IRQ_UnInit(), adf7030_1__SPI_UnInit(), ADF7030_1_NUM_INSTANCES, ADI_ADF7030_1_DEVICE_NOT_OPENED, ADI_ADF7030_1_GPIO_DEV_FAILED, ADI_ADF7030_1_INVALID_HANDLE, ADI_ADF7030_1_SPI_DEV_FAILED, ADI_ADF7030_1_STATE_ENABLED, ADI_ADF7030_1_STATE_NOT_OPENED, ADI_ADF7030_1_SUCCESS, adi_adf7030_1_device::eState, adi_adf7030_1_info::hDevice, and adi_adf7030_1_device::pDevInfo.
adf7030_1__Enable()
ADI_ADF7030_1_RESULT adf7030_1__Enable (ADI_ADF7030_1_HANDLE const hDevice, bool bEnable)
Enable the adf7030-1.
Note
This function initialise device instance memory by copying static reference of ADI_ADF7030_1_SPI_INFO and ADI_ADF7030_1_GPIO_INFO.
Parameters
[in] hDevice Handle to ADF7030-1 device instance.
[in] bEnable Boolean -TRUE to enable Radio PHY -FALSE to disable Radio PHY
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY instance was succesfully setup
ADI_ADF7030_1_DEVICE_NOT_OPENED [D] If PHY instance is not yet opened
ADI_ADF7030_1_INVALID_HANDLE [D] If PHY instance does not exist
ADI_ADF7030_1_FAILURE [D] If PHY instance could not be opened or closed
ADI_ADF7030_1_GPIO_DEV_FAILED [D] If PHY instance GPIO setup failed
See also
adf7030_1__SPI_Init().
adf7030_1__IRQ_Init().
Definition at line 369 of file adf7030-1__core.c.
References adf7030_1__PulseReset(), adf7030_1__SendConfiguration(), adf7030_1__STATE_PhyCMD_WaitReady(), ADI_ADF7030_1_STATE_ENABLED, ADI_ADF7030_1_SUCCESS, adi_adf7030_1_SPI_Info::bPhyErrorCheck, adi_adf7030_1_GPIO_Reset_info::ePort, adi_adf7030_1_device::eState, adi_adf7030_1_GPIO_Reset_info::nPin, adi_adf7030_1_device::pDevInfo, adi_adf7030_1_info::pfEnableFunc, PHY_OFF, adi_adf7030_1_info::pStartupCfg, adi_adf7030_1_info::ResetGPIOInfo, adi_adf7030_1_info::SPIInfo, and adi_adf7030_1_info::StartupCfgSize.
Referenced by adf7030_1__Close().
adf7030_1__EnableHostTrigger()
ADI_ADF7030_1_RESULT adf7030_1__EnableHostTrigger (ADI_ADF7030_1_INFO * pDevInfo, ADI_ADF7030_1_TRIGPIN eTRIG, bool bEnable)
Initialise the Host GPIO Trigger pin to interface with the PHY Radio.
Parameters
[in] pDevInfo Pointer to the ADF7030-1 instance information.
[in] eTRIG PHY Trigger PIN to configure.
Returns
Status
ADI_ADF7030_1_SUCCESS If Host GPIO has been configured for trigger functionality
ADI_ADF7030_1_GPIO_DEV_FAILED If Host GPIO configuration failed
Definition at line 752 of file adf7030-1__core.c.
References ADI_ADF7030_1_GPIO_DEV_FAILED, ADI_ADF7030_1_SUCCESS, adi_adf7030_1_GPIO_Trig_info::ePort, adi_adf7030_1_GPIO_Trig_info::eTrigStatus, HOST_READY, NONE, adi_adf7030_1_GPIO_Trig_info::nPin, and adi_adf7030_1_info::TrigGPIOInfo.
Referenced by adf7030_1__Setup().
adf7030_1__Get_PhyPckConfigAddr()
ADI_ADF7030_1_RESULT adf7030_1__Get_PhyPckConfigAddr (ADI_ADF7030_1_INFO * pDevInfo, uint32_t * pAddr)
Readback the PHY Packet configuration location.
Note
This function is reading address location of the PHY Packet configuration structure and return is value into normalised 32bits address space. This function does not handle SPI communication error.
Parameters
[in] pDevInfo Pointer to the ADF7030-1 instance information.
[out] pAddr Pointer to the write back location for the PHY Packet configuration location.
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY Packet configuration location was succesfully readback.
ADI_ADF7030_1_INVALID_PHY_CONFIGURATION [D] If PHY Packet configuration location is invalid.
Definition at line 1130 of file adf7030-1__core.c.
References DATA_BLOCK_DESCRIPTOR_Type::Addr, adf7030_1__SPI_GetField(), adi_adf7030_1_info::pPROFILE__BLOCK, and adi_adf7030_1_info::SPIInfo.
Referenced by adf7030_1__SetupHostPhyCfg().
adf7030_1__Get_PhyProfileAddr()
ADI_ADF7030_1_RESULT adf7030_1__Get_PhyProfileAddr (ADI_ADF7030_1_INFO * pDevInfo, uint32_t * pAddr)
Readback the PHY Radio profile location.
Note
This function is reading address location of the PHY Radio profile structure and return is value into normalised 32bits address space. This function does not handle SPI communication error.
Parameters
[in] pDevInfo Pointer to the ADF7030-1 instance information.
[out] pAddr Pointer to the write back location for the PHY Radio profile location.
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY Radio profile location was succesfully readback.
ADI_ADF7030_1_INVALID_PHY_CONFIGURATION [D] If PHY Radio profile location is invalid.
Definition at line 1053 of file adf7030-1__core.c.
References adf7030_1__SPI_GetField(), and adi_adf7030_1_info::SPIInfo.
Referenced by adf7030_1__SetupHostPhyCfg().
adf7030_1__Open()
ADI_ADF7030_1_RESULT adf7030_1__Open (uint32_t nDeviceNum, void *const pDeviceMemory, uint32_t nMemSize, ADI_CALLBACK pfCallback, void *const pCBParam, ADI_ADF7030_1_HANDLE *const phDevice)
Opens the adf7030-1 driver.
This opens the ADF7030-1 driver and upon success returns the handle to the driver.
The ADF7030-1 uses SPI for communicating with the host processor.
After the ADF7030-1 driver is opened, the part will be in standby mode. Once the required configuration is done, the API adf7030_1__Setup() and adf7030_1__Enable() should be called prior RX or TX operatoions.
Parameters
[in] nDeviceNum ADF7030-1 device instance number. There can be more than one ADF7030-1 devices on a board. This determines the instance that is to be opened.
[in] pDeviceMemory Memory required for ADF7030-1 device operation.
[in] nMemSize The size of the memory passed in bytes.
[in] pfCallback Application supplied callback function, which will be called by the driver to notify interrupts from the PHY radio.
Upon getting the interrupt callback, application can use the API #adf7030_1__IRQ_GetIntStatus to know what caused the interrupts. It can be one or more of interrupts in the enumeration #ADI_AF7030_1_EXT_IRQn_Msk_Type that could have caused the interrupt.
[in] pCBParam Application supplied callback parameter, which will be passed back when the callback function is called.
[out] phDevice Pointer to a location where the device handle is written.
Returns
Status
ADI_ADF7030_1_SUCCESS If successfully opened the device.
ADI_ADF7030_1_INVALID_DEVICE_NUM [D] If the given device number is outside the number of instances supported.
ADI_ADF7030_1_NULL_POINTER [D] If one of the given pointers are pointing to NULL.
ADI_ADF7030_1_INSUFFICIENT_MEMORY [D] If the given memory is not sufficient to operate the device.
ADI_ADF7030_1_UNALIGNED_MEM_PTR [D] If the given device memory pointer is not aligned to a word boundary.
ADI_ADF7030_1_DEVICE_ALREADY_OPENED [D] If the given device is already opened.
Note
SPI mode is not supported.
See also
adf7030_1__Close()
adf7030_1__Setup()
adf7030_1__Enable()
Definition at line 170 of file adf7030-1__core.c.
References ADF7030_1_NUM_INSTANCES, ADI_ADF7030_1_DEVICE_ALREADY_OPENED, ADI_ADF7030_1_INVALID_DEVICE_NUM, ADI_ADF7030_1_STATE_NOT_OPENED, ADI_ADF7030_1_STATE_OPENED, ADI_ADF7030_1_SUCCESS, adi_adf7030_1_device::eState, adi_adf7030_1_info::hDevice, adi_adf7030_1_info::pCBParam, adi_adf7030_1_device::pDevInfo, and adi_adf7030_1_info::pfCallback.
adf7030_1__PulseReset()
ADI_ADF7030_1_RESULT adf7030_1__PulseReset (ADI_ADF7030_1_INFO * pDevInfo)
Pulse Host GPIO Reset pin.
Parameters
[in] pDevInfo Pointer to the ADF7030-1 instance information.
Returns
Status
ADI_ADF7030_1_SUCCESS If Reset GPIO has been pulsed
ADI_ADF7030_1_GPIO_DEV_FAILED If Reset GPIO failed to pulse
Definition at line 915 of file adf7030-1__core.c.
References ADI_ADF7030_1_GPIO_DEV_FAILED, ADI_ADF7030_1_SUCCESS, adi_adf7030_1_GPIO_Reset_info::ePort, adi_adf7030_1_GPIO_Reset_info::nPin, and adi_adf7030_1_info::ResetGPIOInfo.
Referenced by adf7030_1__Enable().
adf7030_1__PulseTrigger()
ADI_ADF7030_1_RESULT adf7030_1__PulseTrigger (ADI_ADF7030_1_INFO * pDevInfo, ADI_ADF7030_1_TRIGPIN eTRIG)
Pulse Host GPIO Trigger pin.
Parameters
[in] pDevInfo Pointer to the ADF7030-1 instance information.
[in] eTRIG PHY Trigger PIN to configure.
Returns
Status
ADI_ADF7030_1_SUCCESS If Trigger GPIO has been pulsed
ADI_ADF7030_1_GPIO_DEV_FAILED If Trigger GPIO failed to pulse
Definition at line 883 of file adf7030-1__core.c.
References ADI_ADF7030_1_GPIO_DEV_FAILED, ADI_ADF7030_1_SUCCESS, adi_adf7030_1_GPIO_Trig_info::ePort, adi_adf7030_1_GPIO_Trig_info::nPin, and adi_adf7030_1_info::TrigGPIOInfo.
adf7030_1__Set_PhyPckConfigAddr()
ADI_ADF7030_1_RESULT adf7030_1__Set_PhyPckConfigAddr (ADI_ADF7030_1_INFO * pDevInfo, uint32_t Addr)
Set the PHY Packet configuration location.
Note
This function is writing the address location of the PHY Packet configuration structure. This function does not handle SPI communication error.
Parameters
[in] pDevInfo Pointer to the ADF7030-1 instance information.
[in] Addr Address location for the PHY Packet configuration location.
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY Packet configuration location was succesfully written.
ADI_ADF7030_1_INVALID_PHY_CONFIGURATION [D] If PHY Packet configuration location is invalid.
Definition at line 1169 of file adf7030-1__core.c.
References adi_adf7030_1_info::SPIInfo.
adf7030_1__Set_PhyProfileAddr()
ADI_ADF7030_1_RESULT adf7030_1__Set_PhyProfileAddr (ADI_ADF7030_1_INFO * pDevInfo, uint32_t Addr)
Set the PHY Radio profile location.
Note
This function is writing the address location of the PHY Radio profile structure. This function does not handle SPI communication error.
Parameters
[in] pDevInfo Pointer to the ADF7030-1 instance information.
[in] Addr Address location for the PHY Radio profile location.
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY Radio profile location was succesfully written.
ADI_ADF7030_1_INVALID_PHY_CONFIGURATION [D] If PHY Radio profile location is invalid.
Definition at line 1093 of file adf7030-1__core.c.
References adi_adf7030_1_info::SPIInfo.
adf7030_1__Setup()
ADI_ADF7030_1_RESULT adf7030_1__Setup (ADI_ADF7030_1_HANDLE const hDevice, ADI_ADF7030_1_SPI_INFO *const pSPIDevInfo, ADI_ADF7030_1_GPIO_INT_INFO *const pINTDevInfo, ADI_ADF7030_1_GPIO_TRIG_INFO *const pTRIGDevInfo, ADI_ADF7030_1_GPIO_RESET_INFO *const pRESETDevInfo)
Setup the adf7030-1 instance by initialising its device info structure. It also calls adf7030_1__SPI_Init() and adf7030_1__IRQ_Init() to setup underlying SPI driver and GPIO service.
Note
This function initialise device instance memory by copying static reference of ADI_ADF7030_1_SPI_INFO and ADI_ADF7030_1_GPIO_INFO.
Parameters
[in] hDevice Handle to ADF7030-1 device instance.
[in] pSPIDevInfo Pointer to a reference ADF7030-1 instance SPI information structure.
[in] pGPIODevInfo Pointer to a reference ADF7030-1 instance GPIO information structure.
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY instance was succesfully setup
ADI_ADF7030_1_DEVICE_NOT_OPENED [D] If PHY instance is not yet opened
ADI_ADF7030_1_INVALID_HANDLE [D] If PHY instance does not exist
ADI_ADF7030_1_SPI_DEV_FAILED [D] If PHY instance SPI setup failed
ADI_ADF7030_1_GPIO_DEV_FAILED [D] If PHY instance GPIO setup failed
See also
adf7030_1__SPI_Init().
adf7030_1__IRQ_Init().
Definition at line 258 of file adf7030-1__core.c.
References adf7030_1__EnableHostTrigger(), adf7030_1__IRQ_Init(), adf7030_1__SPI_Init(), ADF7030_1_NUM_INT_PIN, ADF7030_1_NUM_TRIG_PIN, ADI_ADF7030_1_GPIO_DEV_FAILED, ADI_ADF7030_1_SPI_DEV_FAILED, ADI_ADF7030_1_SUCCESS, ADI_ADF7030_1_TRIGPIN0, ADI_ADF7030_1_TRIGPIN1, adi_adf7030_1_GPIO_Reset_info::ePort, adi_adf7030_1_info::IntGPIOInfo, adi_adf7030_1_GPIO_Reset_info::nPin, adi_adf7030_1_device::pDevInfo, adi_adf7030_1_info::ResetGPIOInfo, adi_adf7030_1_info::SPIInfo, and adi_adf7030_1_info::TrigGPIOInfo.
adf7030_1__SetupHostPhyCfg()
ADI_ADF7030_1_RESULT adf7030_1__SetupHostPhyCfg (ADI_ADF7030_1_HANDLE const hDevice, void *const pCfgMem, uint32_t nCfgMemSize, MEM_CFG_DESCRIPTOR_Type * pCfgRef, bool bInit)
Initialise the Host shadow configuration of the PHY Radio.
Note
This function initialise host shadow memory configuration buffer using a MEM_CFG_DESCRIPTOR_Type reference passed as argument. see USER_CONFIG_20.h file as a example. It setup the following parameters of the current instance:
pDevInfo->pPROFILE__BLOCK
pDevInfo->pPACKET_CFG__BLOCK
pDevInfo->pTRX_PCKBUFF0__BLOCK
pDevInfo->pTRX_PCKBUFF1__BLOCK If bInit is set, this function will automatically readback from the PHY Radio both radio profile and default generic packet configuration. User should set this parameter if initialisation is done via a *.cfg file.
Parameters
[in] hDevice Handle to ADF7030-1 device instance.
[in] pCfgMem Memory required for Host shadow phy configuration.
[in] nCfgMemSize The size of the pCfgMem memory passed in bytes.
[in] pCfgRef Pointer to the MEM_CFG_DESCRIPTOR_Type reference configuration file to use for initialisation.
[in] bInit Boolean -TRUE to populate pDevInfo->pPROFILE__BLOCK and pDevInfo->pPACKET_CFG__BLOCK -FALSE [D] to skip initialisation from PHY Radio content
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY instance was succesfully setup
ADI_ADF7030_1_SPI_COMM_FAILED [D] If Communication with the PHY Radio failed
ADI_ADF7030_1_INSUFFICIENT_MEMORY [D] If memory buffer is not sufficient to hold shadow configuration
ADI_ADF7030_1_FAILURE [D] If PHY instance could not be opened or closed
Definition at line 519 of file adf7030-1__core.c.
References DATA_BLOCK_DESCRIPTOR_Type::Addr, adf7030_1__Get_PhyPckConfigAddr(), adf7030_1__Get_PhyProfileAddr(), adf7030_1__ReadDataBlock(), ADI_ADF7030_1_INSUFFICIENT_MEMORY, ADI_ADF7030_1_INVALID_PHY_CONFIGURATION, ADI_ADF7030_1_SPI_COMM_FAILED, ADI_ADF7030_1_SUCCESS, MEM_CFG_DESCRIPTOR_Type::BLOCKS, MEM_CFG_DESCRIPTOR_Type::nbBlock, adi_adf7030_1_info::pCfg, DATA_BLOCK_DESCRIPTOR_Type::pData, adi_adf7030_1_device::pDevInfo, MEM_CFG_DESCRIPTOR_Type::pInfo, MEM_CFG_DESCRIPTOR_Type::pNext, adi_adf7030_1_info::pPACKET_CFG__BLOCK, adi_adf7030_1_info::pPROFILE__BLOCK, adi_adf7030_1_info::pRX_PCKBUFF__BLOCK, adi_adf7030_1_info::pTX_PCKBUFF__BLOCK, MEM_CFG_DESCRIPTOR_Type::Size, and adi_adf7030_1_info::SPIInfo.
adf7030_1__SetupHostTrxBuffer()
ADI_ADF7030_1_RESULT adf7030_1__SetupHostTrxBuffer (ADI_ADF7030_1_INFO * pDevInfo, void *const pTrxMem, uint32_t nTrxMemSize)
Initialise the Host shadow TRX payload buffer of the PHY Radio.
Note
This function is using host shadow memory packet configuration structure to initialise current instance parameters in:
pDevInfo->pTRX_PCKBUFF0__BLOCK
pDevInfo->pTRX_PCKBUFF1__BLOCK
Parameters
[in] pDevInfo Pointer to the ADF7030-1 instance information.
[in] pTrxMem Memory required for Host shadow TRX buffer.
[in] nTrxMemSize The size of the pTrxMem memory passed in bytes.
Returns
Status
ADI_ADF7030_1_SUCCESS If PHY TRX payload buffer was succesfully setup
ADI_ADF7030_1_INSUFFICIENT_MEMORY If memory is not sufficient to hold PHY TRX payload buffer
ADI_ADF7030_1_INVALID_PHY_CONFIGURATION [D] If current PHY TRX payload layout is not a supported.
Definition at line 664 of file adf7030-1__core.c.
References DATA_BLOCK_DESCRIPTOR_Type::Addr, ADI_ADF7030_1_INSUFFICIENT_MEMORY, ADI_ADF7030_1_INVALID_PHY_CONFIGURATION, ADI_ADF7030_1_SUCCESS, ADI_GENERIC_PKT_Type::BUFF_CFG0_b, ADI_GENERIC_PKT_Type::BUFF_CFG1_b, DATA_BLOCK_DESCRIPTOR_Type::pData, adi_adf7030_1_info::pPACKET_CFG__BLOCK, adi_adf7030_1_info::pRX_PCKBUFF__BLOCK, and adi_adf7030_1_info::pTX_PCKBUFF__BLOCK.
adf7030_1__SetupPhyTrigger()
ADI_ADF7030_1_RESULT adf7030_1__SetupPhyTrigger (ADI_ADF7030_1_INFO * pDevInfo, ADI_ADF7030_1_TRIGPIN eTRIG, ADI_ADF7030_1_RADIO_STATE goState)
Setup PHY gpio to for external trigger command.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] TRIG PHY Radio TRIG pin to be configured (enum ADI_ADF7030_1_TRIGPIN)
[in] GPIO PHY Radio GPIO pin to be configured (enum ADI_ADF7030_1_GPIO)
[in] goState PHY Radio State to execute. See ADI_ADF7030_1_RADIO_STATE enum for available States.
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio PHY reset was transfert to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
ADI_ADF7030_1_INVALID_OPERATION [D] If Host GPIO trigger has not been previously configured
Definition at line 796 of file adf7030-1__core.c.
References adf7030_1__GPIO_SetCfg(), adf7030_1__SPI_SetField(), ADI_ADF7030_1_TRIGPIN1, adi_adf7030_1_GPIO_Trig_info::ePhyPin, adi_adf7030_1_GPIO_Trig_info::eTrigStatus, GPIO_TRIG_IN0, GPIO_TRIG_IN1, HOST_READY, SM_CONFIG_GPIO_CMD_0_Addr, adi_adf7030_1_info::SPIInfo, and adi_adf7030_1_info::TrigGPIOInfo.