ADF7030-1 Device Drivers API Reference Manual: GPIO Interface
GPIO Interface
ADF7030-1 Driver
Macros
#define adf7030_1__GPIO_PINCFG(ePIN, eCFG) adf7030_1__GPIO_SetCfg(pSPIDevInfo, ePIN, eCFG, false)
Enumerations
enum ADI_ADF7030_1_BUSIO_PIN {
ADF7030_1_IOBUS_PIN0 = 1UL << ADF7030_1_GPIO0,
ADF7030_1_IOBUS_PIN1 = 1UL << ADF7030_1_GPIO1,
ADF7030_1_IOBUS_PIN2 = 1UL << ADF7030_1_GPIO2,
ADF7030_1_IOBUS_PIN3 = 1UL << ADF7030_1_GPIO3,
ADF7030_1_IOBUS_PIN4 = 1UL << ADF7030_1_GPIO4,
ADF7030_1_IOBUS_PIN5 = 1UL << ADF7030_1_GPIO5,
ADF7030_1_IOBUS_PIN6 = 1UL << ADF7030_1_GPIO6,
ADF7030_1_IOBUS_PIN7 = 1UL << ADF7030_1_GPIO7
}
enum ADI_ADF7030_1_GPIO_CFG {
GPIO_TRIG_IN0 = 4,
GPIO_TRIG_IN1 = 5,
GPIO_IRQ_OUT0 = 6,
GPIO_IRQ_OUT1 = 7,
SPORT_TX_DATA = 12,
SPORT_RX_DATA = 13,
SPORT_TRX_CLOCK = 14,
GPIO_IN0 = 16,
GPIO_IN1 = 17,
GPIO_IN2 = 18,
GPIO_IN3 = 19,
GPIO_IN4 = 20,
GPIO_IN5 = 21,
GPIO_IN6 = 22,
GPIO_IN7 = 23,
GPIO_OUT0 = 24,
GPIO_OUT1 = 25,
GPIO_OUT2 = 26,
GPIO_OUT3 = 27,
GPIO_OUT4 = 28,
GPIO_OUT5 = 29,
GPIO_OUT6 = 30,
GPIO_OUT7 = 31,
GPCLK_OUT = 36,
DEBUG = 63
}
enum ADI_ADF7030_1_GPIO_TRIG_EVENT {
RISING_EDGE = 0,
FALLING_EDGE = 1,
BOTH_EDGE = 2,
LOW_LEVEL = 3,
HIGH_LEVEL = 4
}
Functions
ADI_ADF7030_1_RESULT adf7030_1__GPIO_ClrPin (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_BUSIO_PIN ePin)
Clear an individual PHY Radio GPIO pin to 0.
ADI_ADF7030_1_RESULT adf7030_1__GPIO_GetCfg (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_GPIO_PIN eGPIO, ADI_ADF7030_1_GPIO_CFG *peCFG, bool bDirect)
Get individual GPIO configuration from the PHY Radio.
ADI_ADF7030_1_RESULT adf7030_1__GPIO_SetCfg (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_GPIO_PIN eGPIO, ADI_ADF7030_1_GPIO_CFG eCFG, bool bDirect)
Setup individual GPIO configuration on the PHY Radio.
ADI_ADF7030_1_RESULT adf7030_1__GPIO_SetPin (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_BUSIO_PIN ePin)
Set an individual PHY Radio GPIO pin to 1.
Detailed Description
Enumeration Type Documentation
ADI_ADF7030_1_BUSIO_PIN
enum ADI_ADF7030_1_BUSIO_PIN
Enumeration of GPIO dataout bus pins
Enumerator
ADF7030_1_IOBUS_PIN0
General purpose PHY Radio IO Bus pin 0
ADF7030_1_IOBUS_PIN1
General purpose PHY Radio IO Bus pin 1
ADF7030_1_IOBUS_PIN2
General purpose PHY Radio IO Bus pin 2
ADF7030_1_IOBUS_PIN3
General purpose PHY Radio IO Bus pin 3
ADF7030_1_IOBUS_PIN4
General purpose PHY Radio IO Bus pin 4
ADF7030_1_IOBUS_PIN5
General purpose PHY Radio IO Bus pin 5
ADF7030_1_IOBUS_PIN6
General purpose PHY Radio IO Bus pin 6
ADF7030_1_IOBUS_PIN7
General purpose PHY Radio IO Bus pin 7
Definition at line 160 of file adf7030-1__gpio.h.
ADI_ADF7030_1_GPIO_CFG
enum ADI_ADF7030_1_GPIO_CFG
Enumeration of different PHY Radio gpio configuration
Enumerator
GPIO_TRIG_IN0
External IRQ0 input
GPIO_TRIG_IN1
External IRQ1 input
GPIO_IRQ_OUT0
External IRQ0 output
GPIO_IRQ_OUT1
External IRQ1 output
SPORT_TX_DATA
Sport interface baseband TX data input
SPORT_RX_DATA
Sport interface baseband RX data output
SPORT_TRX_CLOCK
Sport interface baseband TRX clock output
GPIO_IN0
General Purpose Input 0
GPIO_IN1
General Purpose Input 1
GPIO_IN2
General Purpose Input 2
GPIO_IN3
General Purpose Input 3
GPIO_IN4
General Purpose Input 4
GPIO_IN5
General Purpose Input 5
GPIO_IN6
General Purpose Input 6
GPIO_IN7
General Purpose Input 7
GPIO_OUT0
General Purpose Output 0
GPIO_OUT1
General Purpose Output 1
GPIO_OUT2
General Purpose Output 2
GPIO_OUT3
General Purpose Output 3
GPIO_OUT4
General Purpose Output 4
GPIO_OUT5
General Purpose Output 5
GPIO_OUT6
General Purpose Output 6
GPIO_OUT7
General Purpose Output 7
GPCLK_OUT
User defined synchronous Clock output
DEBUG
Debug mode
Definition at line 54 of file adf7030-1__gpio.h.
ADI_ADF7030_1_GPIO_TRIG_EVENT
enum ADI_ADF7030_1_GPIO_TRIG_EVENT
Enumeration of Trigger event options
Enumerator
RISING_EDGE
External PHY Radio trigger on a rising edge
FALLING_EDGE
External PHY Radio trigger on a falling edge
BOTH_EDGE
External PHY Radio trigger on eitherrising or falling edge
LOW_LEVEL
External PHY Radio trigger on a low level
HIGH_LEVEL
External PHY Radio trigger on a high level
Definition at line 137 of file adf7030-1__gpio.h.
Function Documentation
adf7030_1__GPIO_ClrPin()
ADI_ADF7030_1_RESULT adf7030_1__GPIO_ClrPin (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_BUSIO_PIN ePin)
Clear an individual PHY Radio GPIO pin to 0.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] eGPIO PHY Radio GPIO pin to be cleared
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio PHY gpio pin output was cleared correctly.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
Definition at line 218 of file adf7030-1__gpio.c.
References adf7030_1__SPI_SetMem32(), and adi_adf7030_1_SPI_Info::eXferResult.
adf7030_1__GPIO_GetCfg()
ADI_ADF7030_1_RESULT adf7030_1__GPIO_GetCfg (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_GPIO_PIN eGPIO, ADI_ADF7030_1_GPIO_CFG * peCFG, bool bDirect)
Get individual GPIO configuration from the PHY Radio.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] GPIO PHY Radio GPIO pin to be configured
[in] pCFG Pointer to PHY Radio GPIO pin configuration (see ADI_ADF7030_1_GPIO_CFG)
[in] bDirect Boolean -TRUE to directly change the current GPIO pin configuration -FALSE to setup GPIO pin configuration in the profile. The Host must issue a CFG_DEV command to trigger the new setting.
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio PHY gpio configuration was read correctly.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
Definition at line 156 of file adf7030-1__gpio.c.
References adf7030_1__SPI_GetField(), and adi_adf7030_1_SPI_Info::eXferResult.
adf7030_1__GPIO_SetCfg()
ADI_ADF7030_1_RESULT adf7030_1__GPIO_SetCfg (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_GPIO_PIN eGPIO, ADI_ADF7030_1_GPIO_CFG eCFG, bool bDirect)
Setup individual GPIO configuration on the PHY Radio.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] GPIO PHY Radio GPIO pin to be configured
[in] CFG PHY Radio GPIO pin configuration desired (see ADI_ADF7030_1_GPIO_CFG)
[in] bDirect Boolean -TRUE to directly change the current GPIO pin configuration -FALSE to setup GPIO pin configuration in the profile. The Host must issue a CFG_DEV command to trigger the new setting.
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio PHY gpio configuration was applied correctly.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
Definition at line 113 of file adf7030-1__gpio.c.
References adf7030_1__SPI_SetField(), and adi_adf7030_1_SPI_Info::eXferResult.
Referenced by adf7030_1__IRQ_SetGPIOPin(), and adf7030_1__SetupPhyTrigger().
adf7030_1__GPIO_SetPin()
ADI_ADF7030_1_RESULT adf7030_1__GPIO_SetPin (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_BUSIO_PIN ePin)
Set an individual PHY Radio GPIO pin to 1.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] eGPIO PHY Radio GPIO pin to be set
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio PHY gpio pin output was asserted correctly.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
Definition at line 190 of file adf7030-1__gpio.c.
References adf7030_1__SPI_SetMem32(), and adi_adf7030_1_SPI_Info::eXferResult.