ADF7030-1 Device Drivers API Reference Manual: Configuration
Configuration
ADF7030-1 Driver
Functions
ADI_ADF7030_1_RESULT adf7030_1__SendConfiguration (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint8_t *pCONFIG, uint32_t Size)
ADI Radio Configuration transfer function.
ADI_ADF7030_1_RESULT adf7030_1__XferCfgSeq (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint8_t *pData, uint32_t Size)
ADI Radio SPI sequence configuration transfer.
Detailed Description
Function Documentation
adf7030_1__SendConfiguration()
ADI_ADF7030_1_RESULT adf7030_1__SendConfiguration (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint8_t * pCONFIG, uint32_t Size)
ADI Radio Configuration transfer function.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pCONFIG Pointer to cfg binary blob
Note
Currently the maximum allowed "Cfg" sequence is limited by ADF7030_1_SPI_BUFFER_SIZE. User must ensure that the ADF7030-1 design center is configured correctly not to exceed this sequence lenght.
Returns
Status
ADI_ADF7030_1_SUCCESS If the configuration was written transfered to the Host.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the configuration transfert failed.
Definition at line 113 of file adf7030-1__cfg.c.
References adf7030_1__XferCfgSeq(), ADI_ADF7030_1_SPI_COMM_FAILED, and ADI_ADF7030_1_SUCCESS.
Referenced by adf7030_1__Enable().
adf7030_1__XferCfgSeq()
ADI_ADF7030_1_RESULT adf7030_1__XferCfgSeq (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint8_t * pData, uint32_t Size)
ADI Radio SPI sequence configuration transfer.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] pData Pointer to cfg sub sequence
Note
Currently the maximum allowed "Cfg" sequence is limited by ADF7030_1_SPI_BUFFER_SIZE. Future revision of the driver will implement automatic sequence split.
Returns
Status
ADI_ADF7030_1_SUCCESS If the configuration was written transfered to the Host.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the configuration transfert failed.
Definition at line 172 of file adf7030-1__cfg.c.
Referenced by adf7030_1__SendConfiguration().