ADF7030-1 Device Drivers API Reference Manual: SPI Command Interface
SPI Command Interface
ADF7030-1 Driver
Macros
#define CMD_NOP 0xFF
#define CMD_RESET 0xC7
#define PMU_CLOCKS_Addr 0x40000C20UL
#define PMU_CLOCKS_Rst 0x00000001UL
Enumerations
enum ADI_ADF7030_1_RADIO_CMD_TYPE {
RADIO_CMD = (0x1 << 7),
SPECIAL_CMD = (0x3 << 6)
}
Functions
ADI_ADF7030_1_RESULT adf7030_1__STATE_PhyCMD (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_RADIO_STATE goState)
Send Radio PHY Command.
ADI_ADF7030_1_RESULT adf7030_1__STATE_PhyCMD_Ex (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_RADIO_EXTENDED ExCmd)
Send Radio PHY Special Command.
ADI_ADF7030_1_RESULT adf7030_1__STATE_PhyCMD_WaitReady (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_RADIO_STATE goState, ADI_ADF7030_1_RADIO_STATE retState)
Send Radio PHY Command and wait util PHY has transition to new state.
ADI_ADF7030_1_RESULT adf7030_1__STATE_PhyShutdown (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo)
Powering off sequence for the PHY Radio.
ADI_ADF7030_1_RESULT adf7030_1__STATE_PhyWakeUp (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo)
ADI_ADF7030_1_RESULT adf7030_1__STATE_Poll_PhyState (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_RADIO_STATE State, uint8_t nRetry)
Polls Radio PHY SPI Status until match is found.
ADI_ADF7030_1_RESULT adf7030_1__STATE_Poll_SpiStatus (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_SPI_STATUS nSPIStatus, uint8_t nSPIStatusMsk, uint8_t nRetry)
Polls Radio PHY SPI Status with NOPs until match is found.
ADI_ADF7030_1_RESULT adf7030_1__STATE_WaitExec (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint8_t nRetry)
Polls Radio PHY SPI Status with NOPs until in Exec mode.
ADI_ADF7030_1_RESULT adf7030_1__STATE_WaitExtIRQ (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint8_t nRetry)
Polls Radio PHY SPI Status with NOPs until External IRQ flag is found.
ADI_ADF7030_1_RESULT adf7030_1__STATE_WaitIdle (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint8_t nRetry)
Polls Radio PHY SPI Status with NOPs until in Idle mode.
ADI_ADF7030_1_RESULT adf7030_1__STATE_WaitReady (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint8_t nRetry)
Polls Radio PHY SPI Status with NOPs until ready for operation.
ADI_ADF7030_1_RESULT adf7030_1__STATE_WaitStateReady (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, ADI_ADF7030_1_RADIO_STATE nState, uint8_t nRetry)
Polls Radio PHY SPI Status with NOPs until ready for operation.
ADI_ADF7030_1_RESULT adf7030_1__XferCmdPoll (ADI_ADF7030_1_SPI_INFO *pSPIDevInfo, uint8_t nPhyCmd, uint32_t nStatusPoll, ADI_ADF7030_1_RADIO_STATE nStatePoll, uint8_t nRetry)
Generic Radio PHY Command Transfers.
Detailed Description
Enumeration Type Documentation
ADI_ADF7030_1_RADIO_CMD_TYPE
enum ADI_ADF7030_1_RADIO_CMD_TYPE
Enumeration of different radio command type
Definition at line 109 of file adf7030-1__state.h.
Function Documentation
adf7030_1__STATE_PhyCMD()
ADI_ADF7030_1_RESULT adf7030_1__STATE_PhyCMD (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_RADIO_STATE goState)
Send Radio PHY Command.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] goState PHY Radio State to execute. See ADI_ADF7030_1_RADIO_STATE enum for available States.
Note
This function does return immediately after issuing a Radio PHY command. The SPIDevInfo.nStatus field get updated with the SPI status returned as the command is issued.
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio PHY command was transfert to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
Definition at line 159 of file adf7030-1__state.c.
References adf7030_1__XferCmdPoll().
adf7030_1__STATE_PhyCMD_Ex()
ADI_ADF7030_1_RESULT adf7030_1__STATE_PhyCMD_Ex (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_RADIO_EXTENDED ExCmd)
Send Radio PHY Special Command.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] ExCmd PHY Radio State to execute. See ADI_ADF7030_1_RADIO_STATE enum for available States.
Note
This function does return immediately after issuing a Radio PHY Special command. The SPIDevInfo.nStatus field get updated with the SPI status returned as the command is issued.
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio PHY Special command was transfert to the adf7030-1.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
Definition at line 191 of file adf7030-1__state.c.
References adf7030_1__XferCmdPoll().
adf7030_1__STATE_PhyCMD_WaitReady()
ADI_ADF7030_1_RESULT adf7030_1__STATE_PhyCMD_WaitReady (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_RADIO_STATE goState, ADI_ADF7030_1_RADIO_STATE retState)
Send Radio PHY Command and wait util PHY has transition to new state.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] goState PHY Radio State to execute. See ADI_ADF7030_1_RADIO_STATE enum for available States.
[in] retState PHY Radio State expected to be in before returning.
Note
This function issues a Radio PHY command according to the goState, the polls the Radio Firmware state for a fix amount of time (up to 255 retries) until retState is entered and the transition status is set to "state" or "idle". The SPIDevInfo.nStatus field get updated with the live SPI status returned during SPI communication.
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio PHY transition to new state.
ADI_ADF7030_1_SPI_DEV_POLL_EXPIRE [D] If the Radio PHY failed to transition to new state.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
Definition at line 229 of file adf7030-1__state.c.
References adf7030_1__XferCmdPoll(), IDLE, and STATE.
Referenced by adf7030_1__Enable().
adf7030_1__STATE_PhyShutdown()
ADI_ADF7030_1_RESULT adf7030_1__STATE_PhyShutdown (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo)
Powering off sequence for the PHY Radio.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio power off was correctly executed.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
Definition at line 103 of file adf7030-1__state.c.
adf7030_1__STATE_Poll_PhyState()
ADI_ADF7030_1_RESULT adf7030_1__STATE_Poll_PhyState (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_RADIO_STATE State, uint8_t nRetry)
Polls Radio PHY SPI Status until match is found.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] State PHY Radio State to match. See ADI_ADF7030_1_RADIO_STATE enum for available States.
[in] nRetry Number of polling retries. Set to Zero, for continuously polling the SPI Status.
Note
This function is polling the Radio PHY State for a fix amount of time (nRetry) until State is reach. The SPIDevInfo.nStatus field get updated with the live SPI status returned during SPI communication.
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio PHY transition to new state.
ADI_ADF7030_1_SPI_DEV_POLL_EXPIRE [D] If the Radio PHY failed to transition to new state.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
Definition at line 515 of file adf7030-1__state.c.
References adf7030_1__XferCmdPoll().
adf7030_1__STATE_Poll_SpiStatus()
ADI_ADF7030_1_RESULT adf7030_1__STATE_Poll_SpiStatus (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_SPI_STATUS nSPIStatus, uint8_t nSPIStatusMsk, uint8_t nRetry)
Polls Radio PHY SPI Status with NOPs until match is found.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] nSPIStatus Radio PHY SPI status to match. See ADI_ADF7030_1_SPI_STATUS structure for available fields.
[in] nSPIStatusMsk Radio PHY SPI status mask to enable.
[in] nRetry Number of polling retry. Set to Zero, for continuous polling the SPI Status.
Note
This function issues a Radio PHY NOP command polling the Radio Firmware state for a fix amount of time (nRetry) until retState is entered and until the transition status is set to ready or idle. The SPIDevInfo.nStatus field get updated with the live SPI status returned during SPI communication.
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio PHY transition to new state.
ADI_ADF7030_1_SPI_DEV_POLL_EXPIRE [D] If the Radio PHY failed to transition to new state.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
Definition at line 472 of file adf7030-1__state.c.
References adf7030_1__XferCmdPoll(), and adi_adf7030_1_SPI_Status::VALUE.
adf7030_1__STATE_WaitExec()
ADI_ADF7030_1_RESULT adf7030_1__STATE_WaitExec (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint8_t nRetry)
Polls Radio PHY SPI Status with NOPs until in Exec mode.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] nRetry Number of polling retry. Set to Zero, for continuous polling the SPI Status.
Note
This function issues a Radio PHY NOP command polling the SPI status for a fix amount of time (nRetry) until state Execution flag is set. The SPIDevInfo.nStatus field get updated with the live SPI status returned during SPI communication.
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio PHY is in Exec state.
ADI_ADF7030_1_SPI_DEV_POLL_EXPIRE [D] If the Radio PHY is not in Exec state.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
Definition at line 308 of file adf7030-1__state.c.
References adf7030_1__XferCmdPoll(), and STATE.
adf7030_1__STATE_WaitExtIRQ()
ADI_ADF7030_1_RESULT adf7030_1__STATE_WaitExtIRQ (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint8_t nRetry)
Polls Radio PHY SPI Status with NOPs until External IRQ flag is found.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] nRetry Number of polling retry. Set to Zero, for continuous polling the SPI Status.
Note
This function issues a Radio PHY NOP command polling the SPI status for a fix amount of time (nRetry) until External IRQ flag is set. The SPIDevInfo.nStatus field get updated with the live SPI status returned during SPI communication.
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio PHY External IRQ flag is found.
ADI_ADF7030_1_SPI_DEV_POLL_EXPIRE [D] If the Radio PHY External IRQ flag is not found.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
Definition at line 384 of file adf7030-1__state.c.
References adf7030_1__XferCmdPoll().
adf7030_1__STATE_WaitIdle()
ADI_ADF7030_1_RESULT adf7030_1__STATE_WaitIdle (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint8_t nRetry)
Polls Radio PHY SPI Status with NOPs until in Idle mode.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] nRetry Number of polling retry. Set to Zero, for continuous polling the SPI Status.
Note
This function issues a Radio PHY NOP command polling the SPI status for a fix amount of time (nRetry) until Idle flag is set. The SPIDevInfo.nStatus field get updated with the live SPI status returned during SPI communication.
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio PHY is in Idle state.
ADI_ADF7030_1_SPI_DEV_POLL_EXPIRE [D] If the Radio PHY is not in Idle state.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
Definition at line 271 of file adf7030-1__state.c.
References adf7030_1__XferCmdPoll(), and IDLE.
adf7030_1__STATE_WaitReady()
ADI_ADF7030_1_RESULT adf7030_1__STATE_WaitReady (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint8_t nRetry)
Polls Radio PHY SPI Status with NOPs until ready for operation.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] nRetry Number of polling retry. Set to Zero, for continuous polling the SPI Status.
Note
This function issues a Radio PHY NOP command polling the SPI status for a fix amount of time (nRetry) until either Idle or State flag is set. The SPIDevInfo.nStatus field get updated with the live SPI status returned during SPI communication.
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio PHY is either in Idle or Exec state.
ADI_ADF7030_1_SPI_DEV_POLL_EXPIRE [D] If the Radio PHY is neither in Idle or Exec state.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
Definition at line 346 of file adf7030-1__state.c.
References adf7030_1__XferCmdPoll(), IDLE, and STATE.
adf7030_1__STATE_WaitStateReady()
ADI_ADF7030_1_RESULT adf7030_1__STATE_WaitStateReady (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, ADI_ADF7030_1_RADIO_STATE nState, uint8_t nRetry)
Polls Radio PHY SPI Status with NOPs until ready for operation.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] nState PHY Radio State expected expected to match.
[in] nRetry Number of polling retry. Set to Zero, for continuous polling the SPI Status.
Note
This function issues a Radio PHY NOP command polling the SPI status for a fix amount of time (nRetry) until either Idle or State flag is set. The SPIDevInfo.nStatus field get updated with the live SPI status returned during SPI communication.
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio PHY is either in Idle or Exec state.
ADI_ADF7030_1_SPI_DEV_POLL_EXPIRE [D] If the Radio PHY is neither in Idle or Exec state.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
Definition at line 424 of file adf7030-1__state.c.
References adf7030_1__XferCmdPoll(), IDLE, and STATE.
adf7030_1__XferCmdPoll()
ADI_ADF7030_1_RESULT adf7030_1__XferCmdPoll (ADI_ADF7030_1_SPI_INFO * pSPIDevInfo, uint8_t nPhyCmd, uint32_t nStatusPoll, ADI_ADF7030_1_RADIO_STATE nStatePoll, uint8_t nRetry)
Generic Radio PHY Command Transfers.
Parameters
[in] pSPIDevInfo Pointer to the SPI device info structure of the ADI RF Driver used to communicate with the adf7030-1 PHY.
[in] PHY_CMD PHY Command from ADI_ADF7030_1_RADIO_STATE.
Note
This function automatically set the pSPIDevInfo->ePhyError The "Wait for cmd_ready bit" is not correct
Returns
Status
ADI_ADF7030_1_SUCCESS If the Radio PHY Command transfers was successful.
ADI_ADF7030_1_SPI_DEV_POLL_EXPIRE [D] If the Radio PHY Command failed.
ADI_ADF7030_1_SPI_COMM_FAILED [D] If the communication with Radio PHY failed.
ADI_ADF7030_1_HW_ERROR [D] Critical Radio PHY Error has occurred.
Definition at line 551 of file adf7030-1__state.c.
References adf7030_1__SPI_ReadWrite_Fast(), ADI_ADF7030_1_SPI_DEV_POLL_EXPIRE, ADI_ADF7030_1_SUCCESS, MISC_FW_Addr, adi_adf7030_1_SPI_Info::nStatus, adi_adf7030_1_SPI_Info::PHY_PNTR, and adi_adf7030_1_SPI_Status::VALUE.
Referenced by adf7030_1__STATE_PhyCMD(), adf7030_1__STATE_PhyCMD_Ex(), adf7030_1__STATE_PhyCMD_WaitReady(), adf7030_1__STATE_Poll_PhyState(), adf7030_1__STATE_Poll_SpiStatus(), adf7030_1__STATE_WaitExec(), adf7030_1__STATE_WaitExtIRQ(), adf7030_1__STATE_WaitIdle(), adf7030_1__STATE_WaitReady(), and adf7030_1__STATE_WaitStateReady().